// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/definition.proto

package apache.rocketmq.v2;

public interface CacheLimitsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.CacheLimits)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>int64 bytes = 2;</code>
   * @return The bytes.
   */
  long getBytes();
}
