// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/admin.proto

package apache.rocketmq.v2;

public interface ChangeLogLevelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.ChangeLogLevelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string remark = 1;</code>
   * @return The remark.
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 1;</code>
   * @return The bytes for remark.
   */
  com.google.protobuf.ByteString
      getRemarkBytes();
}
