// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public interface MetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.Metric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indicates that if client should export local metrics to server.
   * </pre>
   *
   * <code>bool on = 1;</code>
   * @return The on.
   */
  boolean getOn();

  /**
   * <pre>
   * The endpoint that client metrics should be exported to, which is required if the switch is on.
   * </pre>
   *
   * <code>optional .apache.rocketmq.v2.Endpoints metric_endpoints = 2;</code>
   * @return Whether the metricEndpoints field is set.
   */
  boolean hasMetricEndpoints();
  /**
   * <pre>
   * The endpoint that client metrics should be exported to, which is required if the switch is on.
   * </pre>
   *
   * <code>optional .apache.rocketmq.v2.Endpoints metric_endpoints = 2;</code>
   * @return The metricEndpoints.
   */
  apache.rocketmq.v2.Endpoints getMetricEndpoints();
  /**
   * <pre>
   * The endpoint that client metrics should be exported to, which is required if the switch is on.
   * </pre>
   *
   * <code>optional .apache.rocketmq.v2.Endpoints metric_endpoints = 2;</code>
   */
  apache.rocketmq.v2.EndpointsOrBuilder getMetricEndpointsOrBuilder();
}
