// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public final class MQService {
  private MQService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryRouteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryRouteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryRouteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryRouteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryAssignmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryAssignmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryAssignmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryAssignmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ReceiveMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ReceiveMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageResultEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageResultEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_NackMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_NackMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_NackMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_NackMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_EndTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_EndTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_EndTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_EndTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ThreadStackTrace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ThreadStackTrace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_VerifyMessageCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_VerifyMessageCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_VerifyMessageResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_VerifyMessageResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_Publishing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_Publishing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_Subscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_Settings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_Settings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_TelemetryCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n apache/rocketmq/v2/service.proto\022\022apac" +
      "he.rocketmq.v2\032\036google/protobuf/duration" +
      ".proto\032\037google/protobuf/timestamp.proto\032" +
      "#apache/rocketmq/v2/definition.proto\"@\n\021" +
      "QueryRouteRequest\022+\n\005topic\030\001 \001(\0132\034.apach" +
      "e.rocketmq.v2.Resource\"z\n\022QueryRouteResp" +
      "onse\022*\n\006status\030\001 \001(\0132\032.apache.rocketmq.v" +
      "2.Status\0228\n\016message_queues\030\002 \003(\0132 .apach" +
      "e.rocketmq.v2.MessageQueue\"|\n\022SendMessag" +
      "eRequest\022-\n\010messages\030\001 \003(\0132\033.apache.rock" +
      "etmq.v2.Message\0227\n\rmessage_queue\030\002 \001(\0132 " +
      ".apache.rocketmq.v2.MessageQueue\"t\n\023Send" +
      "MessageResponse\022*\n\006status\030\001 \001(\0132\032.apache" +
      ".rocketmq.v2.Status\0221\n\010receipts\030\002 \003(\0132\037." +
      "apache.rocketmq.v2.SendReceipt\"r\n\026QueryA" +
      "ssignmentRequest\022+\n\005topic\030\001 \001(\0132\034.apache" +
      ".rocketmq.v2.Resource\022+\n\005group\030\002 \001(\0132\034.a" +
      "pache.rocketmq.v2.Resource\"z\n\027QueryAssig" +
      "nmentResponse\022*\n\006status\030\001 \001(\0132\032.apache.r" +
      "ocketmq.v2.Status\0223\n\013assignments\030\002 \003(\0132\036" +
      ".apache.rocketmq.v2.Assignment\"\245\002\n\025Recei" +
      "veMessageRequest\022+\n\005group\030\001 \001(\0132\034.apache" +
      ".rocketmq.v2.Resource\0227\n\rmessage_queue\030\002" +
      " \001(\0132 .apache.rocketmq.v2.MessageQueue\022?" +
      "\n\021filter_expression\030\003 \001(\0132$.apache.rocke" +
      "tmq.v2.FilterExpression\022\022\n\nbatch_size\030\004 " +
      "\001(\005\022:\n\022invisible_duration\030\005 \001(\0132\031.google" +
      ".protobuf.DurationH\000\210\001\001B\025\n\023_invisible_du" +
      "ration\"\342\001\n\026ReceiveMessageResponse\022*\n\006sta" +
      "tus\030\001 \001(\0132\032.apache.rocketmq.v2.Status\022-\n" +
      "\010messages\030\002 \003(\0132\033.apache.rocketmq.v2.Mes" +
      "sage\0226\n\022delivery_timestamp\030\003 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\0225\n\022invisible_durati" +
      "on\030\004 \001(\0132\031.google.protobuf.Duration\"=\n\017A" +
      "ckMessageEntry\022\022\n\nmessage_id\030\001 \001(\t\022\026\n\016re" +
      "ceipt_handle\030\002 \001(\t\"\243\001\n\021AckMessageRequest" +
      "\022+\n\005group\030\001 \001(\0132\034.apache.rocketmq.v2.Res" +
      "ource\022+\n\005topic\030\002 \001(\0132\034.apache.rocketmq.v" +
      "2.Resource\0224\n\007entries\030\003 \003(\0132#.apache.roc" +
      "ketmq.v2.AckMessageEntry\"o\n\025AckMessageRe" +
      "sultEntry\022\022\n\nmessage_id\030\001 \001(\t\022\026\n\016receipt" +
      "_handle\030\002 \001(\t\022*\n\006status\030\003 \001(\0132\032.apache.r" +
      "ocketmq.v2.Status\"|\n\022AckMessageResponse\022" +
      "*\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2.Sta" +
      "tus\022:\n\007entries\030\002 \003(\0132).apache.rocketmq.v" +
      "2.AckMessageResultEntry\"\264\001\n\022NackMessageR" +
      "equest\022+\n\005group\030\001 \001(\0132\034.apache.rocketmq." +
      "v2.Resource\022+\n\005topic\030\002 \001(\0132\034.apache.rock" +
      "etmq.v2.Resource\022\026\n\016receipt_handle\030\003 \001(\t" +
      "\022\022\n\nmessage_id\030\004 \001(\t\022\030\n\020delivery_attempt" +
      "\030\005 \001(\005\"A\n\023NackMessageResponse\022*\n\006status\030" +
      "\001 \001(\0132\032.apache.rocketmq.v2.Status\"\347\001\n&Fo" +
      "rwardMessageToDeadLetterQueueRequest\022+\n\005" +
      "group\030\001 \001(\0132\034.apache.rocketmq.v2.Resourc" +
      "e\022+\n\005topic\030\002 \001(\0132\034.apache.rocketmq.v2.Re" +
      "source\022\026\n\016receipt_handle\030\003 \001(\t\022\022\n\nmessag" +
      "e_id\030\004 \001(\t\022\030\n\020delivery_attempt\030\005 \001(\005\022\035\n\025" +
      "max_delivery_attempts\030\006 \001(\005\"U\n\'ForwardMe" +
      "ssageToDeadLetterQueueResponse\022*\n\006status" +
      "\030\001 \001(\0132\032.apache.rocketmq.v2.Status\"N\n\020He" +
      "artbeatRequest\0220\n\005group\030\001 \001(\0132\034.apache.r" +
      "ocketmq.v2.ResourceH\000\210\001\001B\010\n\006_group\"?\n\021He" +
      "artbeatResponse\022*\n\006status\030\001 \001(\0132\032.apache" +
      ".rocketmq.v2.Status\"\375\001\n\025EndTransactionRe" +
      "quest\022+\n\005topic\030\001 \001(\0132\034.apache.rocketmq.v" +
      "2.Resource\022\022\n\nmessage_id\030\002 \001(\t\022\026\n\016transa" +
      "ction_id\030\003 \001(\t\022=\n\nresolution\030\004 \001(\0162).apa" +
      "che.rocketmq.v2.TransactionResolution\0225\n" +
      "\006source\030\005 \001(\0162%.apache.rocketmq.v2.Trans" +
      "actionSource\022\025\n\rtrace_context\030\006 \001(\t\"D\n\026E" +
      "ndTransactionResponse\022*\n\006status\030\001 \001(\0132\032." +
      "apache.rocketmq.v2.Status\"-\n\034PrintThread" +
      "StackTraceCommand\022\r\n\005nonce\030\001 \001(\t\"\205\001\n\020Thr" +
      "eadStackTrace\022\r\n\005nonce\030\001 \001(\t\022*\n\006status\030\002" +
      " \001(\0132\032.apache.rocketmq.v2.Status\022\037\n\022thre" +
      "ad_stack_trace\030\003 \001(\tH\000\210\001\001B\025\n\023_thread_sta" +
      "ck_trace\"S\n\024VerifyMessageCommand\022\r\n\005nonc" +
      "e\030\001 \001(\t\022,\n\007message\030\002 \001(\0132\033.apache.rocket" +
      "mq.v2.Message\"P\n\023VerifyMessageResult\022\r\n\005" +
      "nonce\030\001 \001(\t\022*\n\006status\030\002 \001(\0132\032.apache.roc" +
      "ketmq.v2.Status\"\200\001\n!RecoverOrphanedTrans" +
      "actionCommand\022C\n\036orphaned_transactional_" +
      "message\030\001 \001(\0132\033.apache.rocketmq.v2.Messa" +
      "ge\022\026\n\016transaction_id\030\002 \001(\t\"\251\001\n\nPublishin" +
      "g\022,\n\006topics\030\001 \003(\0132\034.apache.rocketmq.v2.R" +
      "esource\0225\n\014retry_policy\030\002 \001(\0132\037.apache.r" +
      "ocketmq.v2.RetryPolicy\022\037\n\027compress_body_" +
      "threshold\030\003 \001(\005\022\025\n\rmax_body_size\030\004 \001(\005\"\354" +
      "\002\n\014Subscription\0220\n\005group\030\001 \001(\0132\034.apache." +
      "rocketmq.v2.ResourceH\000\210\001\001\022<\n\rsubscriptio" +
      "ns\030\002 \003(\0132%.apache.rocketmq.v2.Subscripti" +
      "onEntry\022\021\n\004fifo\030\003 \001(\010H\001\210\001\001\0227\n\016backoff_po" +
      "licy\030\004 \001(\0132\037.apache.rocketmq.v2.RetryPol" +
      "icy\022\037\n\022receive_batch_size\030\005 \001(\005H\002\210\001\001\022<\n\024" +
      "long_polling_timeout\030\006 \001(\0132\031.google.prot" +
      "obuf.DurationH\003\210\001\001B\010\n\006_groupB\007\n\005_fifoB\025\n" +
      "\023_receive_batch_sizeB\027\n\025_long_polling_ti" +
      "meout\"\347\002\n\010Settings\0228\n\013client_type\030\001 \001(\0162" +
      "\036.apache.rocketmq.v2.ClientTypeH\001\210\001\001\0228\n\014" +
      "access_point\030\002 \001(\0132\035.apache.rocketmq.v2." +
      "EndpointsH\002\210\001\001\0227\n\017request_timeout\030\003 \001(\0132" +
      "\031.google.protobuf.DurationH\003\210\001\001\0224\n\npubli" +
      "shing\030\004 \001(\0132\036.apache.rocketmq.v2.Publish" +
      "ingH\000\0228\n\014subscription\030\005 \001(\0132 .apache.roc" +
      "ketmq.v2.SubscriptionH\000B\t\n\007pub_subB\016\n\014_c" +
      "lient_typeB\017\n\r_access_pointB\022\n\020_request_" +
      "timeout\"\356\003\n\020TelemetryCommand\0220\n\010settings" +
      "\030\001 \001(\0132\034.apache.rocketmq.v2.SettingsH\000\022B" +
      "\n\022thread_stack_trace\030\002 \001(\0132$.apache.rock" +
      "etmq.v2.ThreadStackTraceH\000\022H\n\025verify_mes" +
      "sage_result\030\003 \001(\0132\'.apache.rocketmq.v2.V" +
      "erifyMessageResultH\000\022e\n$recover_orphaned" +
      "_transaction_command\030\004 \001(\01325.apache.rock" +
      "etmq.v2.RecoverOrphanedTransactionComman" +
      "dH\000\022\\\n print_thread_stack_trace_command\030" +
      "\005 \001(\01320.apache.rocketmq.v2.PrintThreadSt" +
      "ackTraceCommandH\000\022J\n\026verify_message_comm" +
      "and\030\006 \001(\0132(.apache.rocketmq.v2.VerifyMes" +
      "sageCommandH\000B\t\n\007command\"\\\n\036NotifyClient" +
      "TerminationRequest\0220\n\005group\030\001 \001(\0132\034.apac" +
      "he.rocketmq.v2.ResourceH\000\210\001\001B\010\n\006_group\"M" +
      "\n\037NotifyClientTerminationResponse\022*\n\006sta" +
      "tus\030\001 \001(\0132\032.apache.rocketmq.v2.Status\"\311\001" +
      "\n\036ChangeInvisibleDurationRequest\022+\n\005grou" +
      "p\030\001 \001(\0132\034.apache.rocketmq.v2.Resource\022+\n" +
      "\005topic\030\002 \001(\0132\034.apache.rocketmq.v2.Resour" +
      "ce\022\026\n\016receipt_handle\030\003 \001(\t\0225\n\022invisible_" +
      "duration\030\004 \001(\0132\031.google.protobuf.Duratio" +
      "n\"e\n\037ChangeInvisibleDurationResponse\022*\n\006" +
      "status\030\001 \001(\0132\032.apache.rocketmq.v2.Status" +
      "\022\026\n\016receipt_handle\030\002 \001(\t2\302\n\n\020MessagingSe" +
      "rvice\022]\n\nQueryRoute\022%.apache.rocketmq.v2" +
      ".QueryRouteRequest\032&.apache.rocketmq.v2." +
      "QueryRouteResponse\"\000\022Z\n\tHeartbeat\022$.apac" +
      "he.rocketmq.v2.HeartbeatRequest\032%.apache" +
      ".rocketmq.v2.HeartbeatResponse\"\000\022`\n\013Send" +
      "Message\022&.apache.rocketmq.v2.SendMessage" +
      "Request\032\'.apache.rocketmq.v2.SendMessage" +
      "Response\"\000\022l\n\017QueryAssignment\022*.apache.r" +
      "ocketmq.v2.QueryAssignmentRequest\032+.apac" +
      "he.rocketmq.v2.QueryAssignmentResponse\"\000" +
      "\022k\n\016ReceiveMessage\022).apache.rocketmq.v2." +
      "ReceiveMessageRequest\032*.apache.rocketmq." +
      "v2.ReceiveMessageResponse\"\0000\001\022]\n\nAckMess" +
      "age\022%.apache.rocketmq.v2.AckMessageReque" +
      "st\032&.apache.rocketmq.v2.AckMessageRespon" +
      "se\"\000\022`\n\013NackMessage\022&.apache.rocketmq.v2" +
      ".NackMessageRequest\032\'.apache.rocketmq.v2" +
      ".NackMessageResponse\"\000\022\234\001\n\037ForwardMessag" +
      "eToDeadLetterQueue\022:.apache.rocketmq.v2." +
      "ForwardMessageToDeadLetterQueueRequest\032;" +
      ".apache.rocketmq.v2.ForwardMessageToDead" +
      "LetterQueueResponse\"\000\022i\n\016EndTransaction\022" +
      ").apache.rocketmq.v2.EndTransactionReque" +
      "st\032*.apache.rocketmq.v2.EndTransactionRe" +
      "sponse\"\000\022]\n\tTelemetry\022$.apache.rocketmq." +
      "v2.TelemetryCommand\032$.apache.rocketmq.v2" +
      ".TelemetryCommand\"\000(\0010\001\022\204\001\n\027NotifyClient" +
      "Termination\0222.apache.rocketmq.v2.NotifyC" +
      "lientTerminationRequest\0323.apache.rocketm" +
      "q.v2.NotifyClientTerminationResponse\"\000\022\204" +
      "\001\n\027ChangeInvisibleDuration\0222.apache.rock" +
      "etmq.v2.ChangeInvisibleDurationRequest\0323" +
      ".apache.rocketmq.v2.ChangeInvisibleDurat" +
      "ionResponse\"\000B<\n\022apache.rocketmq.v2B\tMQS" +
      "erviceP\001\240\001\001\330\001\001\252\002\022Apache.Rocketmq.V2b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          apache.rocketmq.v2.MQDomain.getDescriptor(),
        });
    internal_static_apache_rocketmq_v2_QueryRouteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apache_rocketmq_v2_QueryRouteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryRouteRequest_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_apache_rocketmq_v2_QueryRouteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apache_rocketmq_v2_QueryRouteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryRouteResponse_descriptor,
        new java.lang.String[] { "Status", "MessageQueues", });
    internal_static_apache_rocketmq_v2_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apache_rocketmq_v2_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_SendMessageRequest_descriptor,
        new java.lang.String[] { "Messages", "MessageQueue", });
    internal_static_apache_rocketmq_v2_SendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apache_rocketmq_v2_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_SendMessageResponse_descriptor,
        new java.lang.String[] { "Status", "Receipts", });
    internal_static_apache_rocketmq_v2_QueryAssignmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_apache_rocketmq_v2_QueryAssignmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryAssignmentRequest_descriptor,
        new java.lang.String[] { "Topic", "Group", });
    internal_static_apache_rocketmq_v2_QueryAssignmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_apache_rocketmq_v2_QueryAssignmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryAssignmentResponse_descriptor,
        new java.lang.String[] { "Status", "Assignments", });
    internal_static_apache_rocketmq_v2_ReceiveMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_apache_rocketmq_v2_ReceiveMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ReceiveMessageRequest_descriptor,
        new java.lang.String[] { "Group", "MessageQueue", "FilterExpression", "BatchSize", "InvisibleDuration", "InvisibleDuration", });
    internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor,
        new java.lang.String[] { "Status", "Messages", "DeliveryTimestamp", "InvisibleDuration", });
    internal_static_apache_rocketmq_v2_AckMessageEntry_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_apache_rocketmq_v2_AckMessageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageEntry_descriptor,
        new java.lang.String[] { "MessageId", "ReceiptHandle", });
    internal_static_apache_rocketmq_v2_AckMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_apache_rocketmq_v2_AckMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "Entries", });
    internal_static_apache_rocketmq_v2_AckMessageResultEntry_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_apache_rocketmq_v2_AckMessageResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageResultEntry_descriptor,
        new java.lang.String[] { "MessageId", "ReceiptHandle", "Status", });
    internal_static_apache_rocketmq_v2_AckMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_apache_rocketmq_v2_AckMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageResponse_descriptor,
        new java.lang.String[] { "Status", "Entries", });
    internal_static_apache_rocketmq_v2_NackMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_apache_rocketmq_v2_NackMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_NackMessageRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ReceiptHandle", "MessageId", "DeliveryAttempt", });
    internal_static_apache_rocketmq_v2_NackMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_apache_rocketmq_v2_NackMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_NackMessageResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ReceiptHandle", "MessageId", "DeliveryAttempt", "MaxDeliveryAttempts", });
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_apache_rocketmq_v2_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Group", "Group", });
    internal_static_apache_rocketmq_v2_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_apache_rocketmq_v2_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_EndTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_apache_rocketmq_v2_EndTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_EndTransactionRequest_descriptor,
        new java.lang.String[] { "Topic", "MessageId", "TransactionId", "Resolution", "Source", "TraceContext", });
    internal_static_apache_rocketmq_v2_EndTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_apache_rocketmq_v2_EndTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_EndTransactionResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_descriptor,
        new java.lang.String[] { "Nonce", });
    internal_static_apache_rocketmq_v2_ThreadStackTrace_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_apache_rocketmq_v2_ThreadStackTrace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ThreadStackTrace_descriptor,
        new java.lang.String[] { "Nonce", "Status", "ThreadStackTrace", "ThreadStackTrace", });
    internal_static_apache_rocketmq_v2_VerifyMessageCommand_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_apache_rocketmq_v2_VerifyMessageCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_VerifyMessageCommand_descriptor,
        new java.lang.String[] { "Nonce", "Message", });
    internal_static_apache_rocketmq_v2_VerifyMessageResult_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_apache_rocketmq_v2_VerifyMessageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_VerifyMessageResult_descriptor,
        new java.lang.String[] { "Nonce", "Status", });
    internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_descriptor,
        new java.lang.String[] { "OrphanedTransactionalMessage", "TransactionId", });
    internal_static_apache_rocketmq_v2_Publishing_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_apache_rocketmq_v2_Publishing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_Publishing_descriptor,
        new java.lang.String[] { "Topics", "RetryPolicy", "CompressBodyThreshold", "MaxBodySize", });
    internal_static_apache_rocketmq_v2_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_apache_rocketmq_v2_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_Subscription_descriptor,
        new java.lang.String[] { "Group", "Subscriptions", "Fifo", "BackoffPolicy", "ReceiveBatchSize", "LongPollingTimeout", "Group", "Fifo", "ReceiveBatchSize", "LongPollingTimeout", });
    internal_static_apache_rocketmq_v2_Settings_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_apache_rocketmq_v2_Settings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_Settings_descriptor,
        new java.lang.String[] { "ClientType", "AccessPoint", "RequestTimeout", "Publishing", "Subscription", "PubSub", "ClientType", "AccessPoint", "RequestTimeout", });
    internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_apache_rocketmq_v2_TelemetryCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor,
        new java.lang.String[] { "Settings", "ThreadStackTrace", "VerifyMessageResult", "RecoverOrphanedTransactionCommand", "PrintThreadStackTraceCommand", "VerifyMessageCommand", "Command", });
    internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_descriptor,
        new java.lang.String[] { "Group", "Group", });
    internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ReceiptHandle", "InvisibleDuration", });
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_descriptor,
        new java.lang.String[] { "Status", "ReceiptHandle", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    apache.rocketmq.v2.MQDomain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
