// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public final class MQService {
  private MQService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryRouteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryRouteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryRouteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryRouteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_SendResultEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_SendResultEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryAssignmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryAssignmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_QueryAssignmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_QueryAssignmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ReceiveMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ReceiveMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageResultEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageResultEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_AckMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_AckMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_EndTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_EndTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_EndTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_EndTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ThreadStackTrace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ThreadStackTrace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_VerifyMessageCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_VerifyMessageCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_VerifyMessageResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_VerifyMessageResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_Publishing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_Publishing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_Subscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_Settings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_Settings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_TelemetryCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n apache/rocketmq/v2/service.proto\022\022apac" +
      "he.rocketmq.v2\032\036google/protobuf/duration" +
      ".proto\032#apache/rocketmq/v2/definition.pr" +
      "oto\"r\n\021QueryRouteRequest\022+\n\005topic\030\001 \001(\0132" +
      "\034.apache.rocketmq.v2.Resource\0220\n\tendpoin" +
      "ts\030\002 \001(\0132\035.apache.rocketmq.v2.Endpoints\"" +
      "z\n\022QueryRouteResponse\022*\n\006status\030\001 \001(\0132\032." +
      "apache.rocketmq.v2.Status\0228\n\016message_que" +
      "ues\030\002 \003(\0132 .apache.rocketmq.v2.MessageQu" +
      "eue\"C\n\022SendMessageRequest\022-\n\010messages\030\001 " +
      "\003(\0132\033.apache.rocketmq.v2.Message\"y\n\017Send" +
      "ResultEntry\022*\n\006status\030\001 \001(\0132\032.apache.roc" +
      "ketmq.v2.Status\022\022\n\nmessage_id\030\002 \001(\t\022\026\n\016t" +
      "ransaction_id\030\003 \001(\t\022\016\n\006offset\030\004 \001(\003\"w\n\023S" +
      "endMessageResponse\022*\n\006status\030\001 \001(\0132\032.apa" +
      "che.rocketmq.v2.Status\0224\n\007entries\030\002 \003(\0132" +
      "#.apache.rocketmq.v2.SendResultEntry\"\244\001\n" +
      "\026QueryAssignmentRequest\022+\n\005topic\030\001 \001(\0132\034" +
      ".apache.rocketmq.v2.Resource\022+\n\005group\030\002 " +
      "\001(\0132\034.apache.rocketmq.v2.Resource\0220\n\tend" +
      "points\030\003 \001(\0132\035.apache.rocketmq.v2.Endpoi" +
      "nts\"z\n\027QueryAssignmentResponse\022*\n\006status" +
      "\030\001 \001(\0132\032.apache.rocketmq.v2.Status\0223\n\013as" +
      "signments\030\002 \003(\0132\036.apache.rocketmq.v2.Ass" +
      "ignment\"\271\002\n\025ReceiveMessageRequest\022+\n\005gro" +
      "up\030\001 \001(\0132\034.apache.rocketmq.v2.Resource\0227" +
      "\n\rmessage_queue\030\002 \001(\0132 .apache.rocketmq." +
      "v2.MessageQueue\022?\n\021filter_expression\030\003 \001" +
      "(\0132$.apache.rocketmq.v2.FilterExpression" +
      "\022\022\n\nbatch_size\030\004 \001(\005\022:\n\022invisible_durati" +
      "on\030\005 \001(\0132\031.google.protobuf.DurationH\000\210\001\001" +
      "\022\022\n\nauto_renew\030\006 \001(\010B\025\n\023_invisible_durat" +
      "ion\"\201\001\n\026ReceiveMessageResponse\022,\n\006status" +
      "\030\001 \001(\0132\032.apache.rocketmq.v2.StatusH\000\022.\n\007" +
      "message\030\002 \001(\0132\033.apache.rocketmq.v2.Messa" +
      "geH\000B\t\n\007content\"=\n\017AckMessageEntry\022\022\n\nme" +
      "ssage_id\030\001 \001(\t\022\026\n\016receipt_handle\030\002 \001(\t\"\243" +
      "\001\n\021AckMessageRequest\022+\n\005group\030\001 \001(\0132\034.ap" +
      "ache.rocketmq.v2.Resource\022+\n\005topic\030\002 \001(\013" +
      "2\034.apache.rocketmq.v2.Resource\0224\n\007entrie" +
      "s\030\003 \003(\0132#.apache.rocketmq.v2.AckMessageE" +
      "ntry\"o\n\025AckMessageResultEntry\022\022\n\nmessage" +
      "_id\030\001 \001(\t\022\026\n\016receipt_handle\030\002 \001(\t\022*\n\006sta" +
      "tus\030\003 \001(\0132\032.apache.rocketmq.v2.Status\"|\n" +
      "\022AckMessageResponse\022*\n\006status\030\001 \001(\0132\032.ap" +
      "ache.rocketmq.v2.Status\022:\n\007entries\030\002 \003(\013" +
      "2).apache.rocketmq.v2.AckMessageResultEn" +
      "try\"\347\001\n&ForwardMessageToDeadLetterQueueR" +
      "equest\022+\n\005group\030\001 \001(\0132\034.apache.rocketmq." +
      "v2.Resource\022+\n\005topic\030\002 \001(\0132\034.apache.rock" +
      "etmq.v2.Resource\022\026\n\016receipt_handle\030\003 \001(\t" +
      "\022\022\n\nmessage_id\030\004 \001(\t\022\030\n\020delivery_attempt" +
      "\030\005 \001(\005\022\035\n\025max_delivery_attempts\030\006 \001(\005\"U\n" +
      "\'ForwardMessageToDeadLetterQueueResponse" +
      "\022*\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2.St" +
      "atus\"\203\001\n\020HeartbeatRequest\0220\n\005group\030\001 \001(\013" +
      "2\034.apache.rocketmq.v2.ResourceH\000\210\001\001\0223\n\013c" +
      "lient_type\030\002 \001(\0162\036.apache.rocketmq.v2.Cl" +
      "ientTypeB\010\n\006_group\"?\n\021HeartbeatResponse\022" +
      "*\n\006status\030\001 \001(\0132\032.apache.rocketmq.v2.Sta" +
      "tus\"\375\001\n\025EndTransactionRequest\022+\n\005topic\030\001" +
      " \001(\0132\034.apache.rocketmq.v2.Resource\022\022\n\nme" +
      "ssage_id\030\002 \001(\t\022\026\n\016transaction_id\030\003 \001(\t\022=" +
      "\n\nresolution\030\004 \001(\0162).apache.rocketmq.v2." +
      "TransactionResolution\0225\n\006source\030\005 \001(\0162%." +
      "apache.rocketmq.v2.TransactionSource\022\025\n\r" +
      "trace_context\030\006 \001(\t\"D\n\026EndTransactionRes" +
      "ponse\022*\n\006status\030\001 \001(\0132\032.apache.rocketmq." +
      "v2.Status\"-\n\034PrintThreadStackTraceComman" +
      "d\022\r\n\005nonce\030\001 \001(\t\"Y\n\020ThreadStackTrace\022\r\n\005" +
      "nonce\030\001 \001(\t\022\037\n\022thread_stack_trace\030\002 \001(\tH" +
      "\000\210\001\001B\025\n\023_thread_stack_trace\"\214\001\n\024VerifyMe" +
      "ssageCommand\022\r\n\005nonce\030\001 \001(\t\0227\n\rmessage_q" +
      "ueue\030\002 \001(\0132 .apache.rocketmq.v2.MessageQ" +
      "ueue\022,\n\007message\030\003 \001(\0132\033.apache.rocketmq." +
      "v2.Message\"$\n\023VerifyMessageResult\022\r\n\005non" +
      "ce\030\001 \001(\t\"\271\001\n!RecoverOrphanedTransactionC" +
      "ommand\0227\n\rmessage_queue\030\001 \001(\0132 .apache.r" +
      "ocketmq.v2.MessageQueue\022C\n\036orphaned_tran" +
      "sactional_message\030\002 \001(\0132\033.apache.rocketm" +
      "q.v2.Message\022\026\n\016transaction_id\030\003 \001(\t\"r\n\n" +
      "Publishing\022,\n\006topics\030\001 \003(\0132\034.apache.rock" +
      "etmq.v2.Resource\022\037\n\027compress_body_thresh" +
      "old\030\002 \001(\005\022\025\n\rmax_body_size\030\003 \001(\005\"\263\002\n\014Sub" +
      "scription\0220\n\005group\030\001 \001(\0132\034.apache.rocket" +
      "mq.v2.ResourceH\000\210\001\001\022<\n\rsubscriptions\030\002 \003" +
      "(\0132%.apache.rocketmq.v2.SubscriptionEntr" +
      "y\022\021\n\004fifo\030\003 \001(\010H\001\210\001\001\022\037\n\022receive_batch_si" +
      "ze\030\004 \001(\005H\002\210\001\001\022<\n\024long_polling_timeout\030\005 " +
      "\001(\0132\031.google.protobuf.DurationH\003\210\001\001B\010\n\006_" +
      "groupB\007\n\005_fifoB\025\n\023_receive_batch_sizeB\027\n" +
      "\025_long_polling_timeout\"Y\n\006Metric\022\n\n\002on\030\001" +
      " \001(\010\0225\n\tendpoints\030\002 \001(\0132\035.apache.rocketm" +
      "q.v2.EndpointsH\000\210\001\001B\014\n\n_endpoints\"\220\004\n\010Se" +
      "ttings\0228\n\013client_type\030\001 \001(\0162\036.apache.roc" +
      "ketmq.v2.ClientTypeH\001\210\001\001\0228\n\014access_point" +
      "\030\002 \001(\0132\035.apache.rocketmq.v2.EndpointsH\002\210" +
      "\001\001\022<\n\016backoff_policy\030\003 \001(\0132\037.apache.rock" +
      "etmq.v2.RetryPolicyH\003\210\001\001\0227\n\017request_time" +
      "out\030\004 \001(\0132\031.google.protobuf.DurationH\004\210\001" +
      "\001\0224\n\npublishing\030\005 \001(\0132\036.apache.rocketmq." +
      "v2.PublishingH\000\0228\n\014subscription\030\006 \001(\0132 ." +
      "apache.rocketmq.v2.SubscriptionH\000\022*\n\nuse" +
      "r_agent\030\007 \001(\0132\026.apache.rocketmq.v2.UA\022*\n" +
      "\006metric\030\010 \001(\0132\032.apache.rocketmq.v2.Metri" +
      "cB\t\n\007pub_subB\016\n\014_client_typeB\017\n\r_access_" +
      "pointB\021\n\017_backoff_policyB\022\n\020_request_tim" +
      "eout\"\252\004\n\020TelemetryCommand\022/\n\006status\030\001 \001(" +
      "\0132\032.apache.rocketmq.v2.StatusH\001\210\001\001\0220\n\010se" +
      "ttings\030\002 \001(\0132\034.apache.rocketmq.v2.Settin" +
      "gsH\000\022B\n\022thread_stack_trace\030\003 \001(\0132$.apach" +
      "e.rocketmq.v2.ThreadStackTraceH\000\022H\n\025veri" +
      "fy_message_result\030\004 \001(\0132\'.apache.rocketm" +
      "q.v2.VerifyMessageResultH\000\022e\n$recover_or" +
      "phaned_transaction_command\030\005 \001(\01325.apach" +
      "e.rocketmq.v2.RecoverOrphanedTransaction" +
      "CommandH\000\022\\\n print_thread_stack_trace_co" +
      "mmand\030\006 \001(\01320.apache.rocketmq.v2.PrintTh" +
      "readStackTraceCommandH\000\022J\n\026verify_messag" +
      "e_command\030\007 \001(\0132(.apache.rocketmq.v2.Ver" +
      "ifyMessageCommandH\000B\t\n\007commandB\t\n\007_statu" +
      "s\"\\\n\036NotifyClientTerminationRequest\0220\n\005g" +
      "roup\030\001 \001(\0132\034.apache.rocketmq.v2.Resource" +
      "H\000\210\001\001B\010\n\006_group\"M\n\037NotifyClientTerminati" +
      "onResponse\022*\n\006status\030\001 \001(\0132\032.apache.rock" +
      "etmq.v2.Status\"\335\001\n\036ChangeInvisibleDurati" +
      "onRequest\022+\n\005group\030\001 \001(\0132\034.apache.rocket" +
      "mq.v2.Resource\022+\n\005topic\030\002 \001(\0132\034.apache.r" +
      "ocketmq.v2.Resource\022\026\n\016receipt_handle\030\003 " +
      "\001(\t\0225\n\022invisible_duration\030\004 \001(\0132\031.google" +
      ".protobuf.Duration\022\022\n\nmessage_id\030\005 \001(\t\"e" +
      "\n\037ChangeInvisibleDurationResponse\022*\n\006sta" +
      "tus\030\001 \001(\0132\032.apache.rocketmq.v2.Status\022\026\n" +
      "\016receipt_handle\030\002 \001(\t2\340\t\n\020MessagingServi" +
      "ce\022]\n\nQueryRoute\022%.apache.rocketmq.v2.Qu" +
      "eryRouteRequest\032&.apache.rocketmq.v2.Que" +
      "ryRouteResponse\"\000\022Z\n\tHeartbeat\022$.apache." +
      "rocketmq.v2.HeartbeatRequest\032%.apache.ro" +
      "cketmq.v2.HeartbeatResponse\"\000\022`\n\013SendMes" +
      "sage\022&.apache.rocketmq.v2.SendMessageReq" +
      "uest\032\'.apache.rocketmq.v2.SendMessageRes" +
      "ponse\"\000\022l\n\017QueryAssignment\022*.apache.rock" +
      "etmq.v2.QueryAssignmentRequest\032+.apache." +
      "rocketmq.v2.QueryAssignmentResponse\"\000\022k\n" +
      "\016ReceiveMessage\022).apache.rocketmq.v2.Rec" +
      "eiveMessageRequest\032*.apache.rocketmq.v2." +
      "ReceiveMessageResponse\"\0000\001\022]\n\nAckMessage" +
      "\022%.apache.rocketmq.v2.AckMessageRequest\032" +
      "&.apache.rocketmq.v2.AckMessageResponse\"" +
      "\000\022\234\001\n\037ForwardMessageToDeadLetterQueue\022:." +
      "apache.rocketmq.v2.ForwardMessageToDeadL" +
      "etterQueueRequest\032;.apache.rocketmq.v2.F" +
      "orwardMessageToDeadLetterQueueResponse\"\000" +
      "\022i\n\016EndTransaction\022).apache.rocketmq.v2." +
      "EndTransactionRequest\032*.apache.rocketmq." +
      "v2.EndTransactionResponse\"\000\022]\n\tTelemetry" +
      "\022$.apache.rocketmq.v2.TelemetryCommand\032$" +
      ".apache.rocketmq.v2.TelemetryCommand\"\000(\001" +
      "0\001\022\204\001\n\027NotifyClientTermination\0222.apache." +
      "rocketmq.v2.NotifyClientTerminationReque" +
      "st\0323.apache.rocketmq.v2.NotifyClientTerm" +
      "inationResponse\"\000\022\204\001\n\027ChangeInvisibleDur" +
      "ation\0222.apache.rocketmq.v2.ChangeInvisib" +
      "leDurationRequest\0323.apache.rocketmq.v2.C" +
      "hangeInvisibleDurationResponse\"\000B<\n\022apac" +
      "he.rocketmq.v2B\tMQServiceP\001\240\001\001\330\001\001\252\002\022Apac" +
      "he.Rocketmq.V2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          apache.rocketmq.v2.MQDomain.getDescriptor(),
        });
    internal_static_apache_rocketmq_v2_QueryRouteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apache_rocketmq_v2_QueryRouteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryRouteRequest_descriptor,
        new java.lang.String[] { "Topic", "Endpoints", });
    internal_static_apache_rocketmq_v2_QueryRouteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apache_rocketmq_v2_QueryRouteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryRouteResponse_descriptor,
        new java.lang.String[] { "Status", "MessageQueues", });
    internal_static_apache_rocketmq_v2_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apache_rocketmq_v2_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_SendMessageRequest_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_apache_rocketmq_v2_SendResultEntry_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apache_rocketmq_v2_SendResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_SendResultEntry_descriptor,
        new java.lang.String[] { "Status", "MessageId", "TransactionId", "Offset", });
    internal_static_apache_rocketmq_v2_SendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_apache_rocketmq_v2_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_SendMessageResponse_descriptor,
        new java.lang.String[] { "Status", "Entries", });
    internal_static_apache_rocketmq_v2_QueryAssignmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_apache_rocketmq_v2_QueryAssignmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryAssignmentRequest_descriptor,
        new java.lang.String[] { "Topic", "Group", "Endpoints", });
    internal_static_apache_rocketmq_v2_QueryAssignmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_apache_rocketmq_v2_QueryAssignmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_QueryAssignmentResponse_descriptor,
        new java.lang.String[] { "Status", "Assignments", });
    internal_static_apache_rocketmq_v2_ReceiveMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_apache_rocketmq_v2_ReceiveMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ReceiveMessageRequest_descriptor,
        new java.lang.String[] { "Group", "MessageQueue", "FilterExpression", "BatchSize", "InvisibleDuration", "AutoRenew", "InvisibleDuration", });
    internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Content", });
    internal_static_apache_rocketmq_v2_AckMessageEntry_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_apache_rocketmq_v2_AckMessageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageEntry_descriptor,
        new java.lang.String[] { "MessageId", "ReceiptHandle", });
    internal_static_apache_rocketmq_v2_AckMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_apache_rocketmq_v2_AckMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "Entries", });
    internal_static_apache_rocketmq_v2_AckMessageResultEntry_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_apache_rocketmq_v2_AckMessageResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageResultEntry_descriptor,
        new java.lang.String[] { "MessageId", "ReceiptHandle", "Status", });
    internal_static_apache_rocketmq_v2_AckMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_apache_rocketmq_v2_AckMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_AckMessageResponse_descriptor,
        new java.lang.String[] { "Status", "Entries", });
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ReceiptHandle", "MessageId", "DeliveryAttempt", "MaxDeliveryAttempts", });
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ForwardMessageToDeadLetterQueueResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_apache_rocketmq_v2_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Group", "ClientType", "Group", });
    internal_static_apache_rocketmq_v2_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_apache_rocketmq_v2_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_EndTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_apache_rocketmq_v2_EndTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_EndTransactionRequest_descriptor,
        new java.lang.String[] { "Topic", "MessageId", "TransactionId", "Resolution", "Source", "TraceContext", });
    internal_static_apache_rocketmq_v2_EndTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_apache_rocketmq_v2_EndTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_EndTransactionResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_PrintThreadStackTraceCommand_descriptor,
        new java.lang.String[] { "Nonce", });
    internal_static_apache_rocketmq_v2_ThreadStackTrace_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_apache_rocketmq_v2_ThreadStackTrace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ThreadStackTrace_descriptor,
        new java.lang.String[] { "Nonce", "ThreadStackTrace", "ThreadStackTrace", });
    internal_static_apache_rocketmq_v2_VerifyMessageCommand_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_apache_rocketmq_v2_VerifyMessageCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_VerifyMessageCommand_descriptor,
        new java.lang.String[] { "Nonce", "MessageQueue", "Message", });
    internal_static_apache_rocketmq_v2_VerifyMessageResult_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_apache_rocketmq_v2_VerifyMessageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_VerifyMessageResult_descriptor,
        new java.lang.String[] { "Nonce", });
    internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_RecoverOrphanedTransactionCommand_descriptor,
        new java.lang.String[] { "MessageQueue", "OrphanedTransactionalMessage", "TransactionId", });
    internal_static_apache_rocketmq_v2_Publishing_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_apache_rocketmq_v2_Publishing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_Publishing_descriptor,
        new java.lang.String[] { "Topics", "CompressBodyThreshold", "MaxBodySize", });
    internal_static_apache_rocketmq_v2_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_apache_rocketmq_v2_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_Subscription_descriptor,
        new java.lang.String[] { "Group", "Subscriptions", "Fifo", "ReceiveBatchSize", "LongPollingTimeout", "Group", "Fifo", "ReceiveBatchSize", "LongPollingTimeout", });
    internal_static_apache_rocketmq_v2_Metric_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_apache_rocketmq_v2_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_Metric_descriptor,
        new java.lang.String[] { "On", "Endpoints", "Endpoints", });
    internal_static_apache_rocketmq_v2_Settings_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_apache_rocketmq_v2_Settings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_Settings_descriptor,
        new java.lang.String[] { "ClientType", "AccessPoint", "BackoffPolicy", "RequestTimeout", "Publishing", "Subscription", "UserAgent", "Metric", "PubSub", "ClientType", "AccessPoint", "BackoffPolicy", "RequestTimeout", });
    internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_apache_rocketmq_v2_TelemetryCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_TelemetryCommand_descriptor,
        new java.lang.String[] { "Status", "Settings", "ThreadStackTrace", "VerifyMessageResult", "RecoverOrphanedTransactionCommand", "PrintThreadStackTraceCommand", "VerifyMessageCommand", "Command", "Status", });
    internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_NotifyClientTerminationRequest_descriptor,
        new java.lang.String[] { "Group", "Group", });
    internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_NotifyClientTerminationResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ChangeInvisibleDurationRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ReceiptHandle", "InvisibleDuration", "MessageId", });
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v2_ChangeInvisibleDurationResponse_descriptor,
        new java.lang.String[] { "Status", "ReceiptHandle", });
    com.google.protobuf.DurationProto.getDescriptor();
    apache.rocketmq.v2.MQDomain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
