// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public interface PullMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.PullMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  apache.rocketmq.v2.Status getStatus();
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   */
  apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>int64 min_offset = 2;</code>
   * @return The minOffset.
   */
  long getMinOffset();

  /**
   * <code>int64 next_offset = 3;</code>
   * @return The nextOffset.
   */
  long getNextOffset();

  /**
   * <code>int64 max_offset = 4;</code>
   * @return The maxOffset.
   */
  long getMaxOffset();

  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 5;</code>
   */
  java.util.List<apache.rocketmq.v2.Message> 
      getMessagesList();
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 5;</code>
   */
  apache.rocketmq.v2.Message getMessages(int index);
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 5;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 5;</code>
   */
  java.util.List<? extends apache.rocketmq.v2.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 5;</code>
   */
  apache.rocketmq.v2.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
