// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.ReceiveMessageResponse}
 */
public final class ReceiveMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.ReceiveMessageResponse)
    ReceiveMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReceiveMessageResponse.newBuilder() to construct.
  private ReceiveMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReceiveMessageResponse() {
    messages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReceiveMessageResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReceiveMessageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            apache.rocketmq.v2.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(apache.rocketmq.v2.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              messages_ = new java.util.ArrayList<apache.rocketmq.v2.Message>();
              mutable_bitField0_ |= 0x00000001;
            }
            messages_.add(
                input.readMessage(apache.rocketmq.v2.Message.parser(), extensionRegistry));
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (deliveryTimestamp_ != null) {
              subBuilder = deliveryTimestamp_.toBuilder();
            }
            deliveryTimestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deliveryTimestamp_);
              deliveryTimestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (invisibleDuration_ != null) {
              subBuilder = invisibleDuration_.toBuilder();
            }
            invisibleDuration_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(invisibleDuration_);
              invisibleDuration_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        messages_ = java.util.Collections.unmodifiableList(messages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.ReceiveMessageResponse.class, apache.rocketmq.v2.ReceiveMessageResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private apache.rocketmq.v2.Status status_;
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Status getStatus() {
    return status_ == null ? apache.rocketmq.v2.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.apache.rocketmq.v2.Status status = 1;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int MESSAGES_FIELD_NUMBER = 2;
  private java.util.List<apache.rocketmq.v2.Message> messages_;
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  @java.lang.Override
  public java.util.List<apache.rocketmq.v2.Message> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends apache.rocketmq.v2.MessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  @java.lang.Override
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.Message getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.MessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }

  public static final int DELIVERY_TIMESTAMP_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp deliveryTimestamp_;
  /**
   * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
   * @return Whether the deliveryTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasDeliveryTimestamp() {
    return deliveryTimestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
   * @return The deliveryTimestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeliveryTimestamp() {
    return deliveryTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deliveryTimestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDeliveryTimestampOrBuilder() {
    return getDeliveryTimestamp();
  }

  public static final int INVISIBLE_DURATION_FIELD_NUMBER = 4;
  private com.google.protobuf.Duration invisibleDuration_;
  /**
   * <code>.google.protobuf.Duration invisible_duration = 4;</code>
   * @return Whether the invisibleDuration field is set.
   */
  @java.lang.Override
  public boolean hasInvisibleDuration() {
    return invisibleDuration_ != null;
  }
  /**
   * <code>.google.protobuf.Duration invisible_duration = 4;</code>
   * @return The invisibleDuration.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getInvisibleDuration() {
    return invisibleDuration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : invisibleDuration_;
  }
  /**
   * <code>.google.protobuf.Duration invisible_duration = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getInvisibleDurationOrBuilder() {
    return getInvisibleDuration();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(1, getStatus());
    }
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(2, messages_.get(i));
    }
    if (deliveryTimestamp_ != null) {
      output.writeMessage(3, getDeliveryTimestamp());
    }
    if (invisibleDuration_ != null) {
      output.writeMessage(4, getInvisibleDuration());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, messages_.get(i));
    }
    if (deliveryTimestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDeliveryTimestamp());
    }
    if (invisibleDuration_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getInvisibleDuration());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.ReceiveMessageResponse)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.ReceiveMessageResponse other = (apache.rocketmq.v2.ReceiveMessageResponse) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getMessagesList()
        .equals(other.getMessagesList())) return false;
    if (hasDeliveryTimestamp() != other.hasDeliveryTimestamp()) return false;
    if (hasDeliveryTimestamp()) {
      if (!getDeliveryTimestamp()
          .equals(other.getDeliveryTimestamp())) return false;
    }
    if (hasInvisibleDuration() != other.hasInvisibleDuration()) return false;
    if (hasInvisibleDuration()) {
      if (!getInvisibleDuration()
          .equals(other.getInvisibleDuration())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (getMessagesCount() > 0) {
      hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesList().hashCode();
    }
    if (hasDeliveryTimestamp()) {
      hash = (37 * hash) + DELIVERY_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryTimestamp().hashCode();
    }
    if (hasInvisibleDuration()) {
      hash = (37 * hash) + INVISIBLE_DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getInvisibleDuration().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReceiveMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.ReceiveMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.ReceiveMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.ReceiveMessageResponse)
      apache.rocketmq.v2.ReceiveMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.ReceiveMessageResponse.class, apache.rocketmq.v2.ReceiveMessageResponse.Builder.class);
    }

    // Construct using apache.rocketmq.v2.ReceiveMessageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        messagesBuilder_.clear();
      }
      if (deliveryTimestampBuilder_ == null) {
        deliveryTimestamp_ = null;
      } else {
        deliveryTimestamp_ = null;
        deliveryTimestampBuilder_ = null;
      }
      if (invisibleDurationBuilder_ == null) {
        invisibleDuration_ = null;
      } else {
        invisibleDuration_ = null;
        invisibleDurationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReceiveMessageResponse_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReceiveMessageResponse getDefaultInstanceForType() {
      return apache.rocketmq.v2.ReceiveMessageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReceiveMessageResponse build() {
      apache.rocketmq.v2.ReceiveMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReceiveMessageResponse buildPartial() {
      apache.rocketmq.v2.ReceiveMessageResponse result = new apache.rocketmq.v2.ReceiveMessageResponse(this);
      int from_bitField0_ = bitField0_;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (messagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
      if (deliveryTimestampBuilder_ == null) {
        result.deliveryTimestamp_ = deliveryTimestamp_;
      } else {
        result.deliveryTimestamp_ = deliveryTimestampBuilder_.build();
      }
      if (invisibleDurationBuilder_ == null) {
        result.invisibleDuration_ = invisibleDuration_;
      } else {
        result.invisibleDuration_ = invisibleDurationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.ReceiveMessageResponse) {
        return mergeFrom((apache.rocketmq.v2.ReceiveMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.ReceiveMessageResponse other) {
      if (other == apache.rocketmq.v2.ReceiveMessageResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (messagesBuilder_ == null) {
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
      } else {
        if (!other.messages_.isEmpty()) {
          if (messagesBuilder_.isEmpty()) {
            messagesBuilder_.dispose();
            messagesBuilder_ = null;
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessagesFieldBuilder() : null;
          } else {
            messagesBuilder_.addAllMessages(other.messages_);
          }
        }
      }
      if (other.hasDeliveryTimestamp()) {
        mergeDeliveryTimestamp(other.getDeliveryTimestamp());
      }
      if (other.hasInvisibleDuration()) {
        mergeInvisibleDuration(other.getInvisibleDuration());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.ReceiveMessageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.ReceiveMessageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private apache.rocketmq.v2.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     * @return The status.
     */
    public apache.rocketmq.v2.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? apache.rocketmq.v2.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder setStatus(apache.rocketmq.v2.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder setStatus(
        apache.rocketmq.v2.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder mergeStatus(apache.rocketmq.v2.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            apache.rocketmq.v2.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public apache.rocketmq.v2.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    public apache.rocketmq.v2.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            apache.rocketmq.v2.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Status, apache.rocketmq.v2.Status.Builder, apache.rocketmq.v2.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private java.util.List<apache.rocketmq.v2.Message> messages_ =
      java.util.Collections.emptyList();
    private void ensureMessagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messages_ = new java.util.ArrayList<apache.rocketmq.v2.Message>(messages_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        apache.rocketmq.v2.Message, apache.rocketmq.v2.Message.Builder, apache.rocketmq.v2.MessageOrBuilder> messagesBuilder_;

    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public java.util.List<apache.rocketmq.v2.Message> getMessagesList() {
      if (messagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messages_);
      } else {
        return messagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public int getMessagesCount() {
      if (messagesBuilder_ == null) {
        return messages_.size();
      } else {
        return messagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public apache.rocketmq.v2.Message getMessages(int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);
      } else {
        return messagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder setMessages(
        int index, apache.rocketmq.v2.Message value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder setMessages(
        int index, apache.rocketmq.v2.Message.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.set(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder addMessages(apache.rocketmq.v2.Message value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder addMessages(
        int index, apache.rocketmq.v2.Message value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(index, value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder addMessages(
        apache.rocketmq.v2.Message.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder addMessages(
        int index, apache.rocketmq.v2.Message.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends apache.rocketmq.v2.Message> values) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
      } else {
        messagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public Builder removeMessages(int index) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.remove(index);
        onChanged();
      } else {
        messagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public apache.rocketmq.v2.Message.Builder getMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public apache.rocketmq.v2.MessageOrBuilder getMessagesOrBuilder(
        int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);  } else {
        return messagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public java.util.List<? extends apache.rocketmq.v2.MessageOrBuilder> 
         getMessagesOrBuilderList() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messages_);
      }
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public apache.rocketmq.v2.Message.Builder addMessagesBuilder() {
      return getMessagesFieldBuilder().addBuilder(
          apache.rocketmq.v2.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public apache.rocketmq.v2.Message.Builder addMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().addBuilder(
          index, apache.rocketmq.v2.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .apache.rocketmq.v2.Message messages = 2;</code>
     */
    public java.util.List<apache.rocketmq.v2.Message.Builder> 
         getMessagesBuilderList() {
      return getMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        apache.rocketmq.v2.Message, apache.rocketmq.v2.Message.Builder, apache.rocketmq.v2.MessageOrBuilder> 
        getMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            apache.rocketmq.v2.Message, apache.rocketmq.v2.Message.Builder, apache.rocketmq.v2.MessageOrBuilder>(
                messages_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }

    private com.google.protobuf.Timestamp deliveryTimestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deliveryTimestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     * @return Whether the deliveryTimestamp field is set.
     */
    public boolean hasDeliveryTimestamp() {
      return deliveryTimestampBuilder_ != null || deliveryTimestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     * @return The deliveryTimestamp.
     */
    public com.google.protobuf.Timestamp getDeliveryTimestamp() {
      if (deliveryTimestampBuilder_ == null) {
        return deliveryTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deliveryTimestamp_;
      } else {
        return deliveryTimestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder setDeliveryTimestamp(com.google.protobuf.Timestamp value) {
      if (deliveryTimestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deliveryTimestamp_ = value;
        onChanged();
      } else {
        deliveryTimestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder setDeliveryTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (deliveryTimestampBuilder_ == null) {
        deliveryTimestamp_ = builderForValue.build();
        onChanged();
      } else {
        deliveryTimestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder mergeDeliveryTimestamp(com.google.protobuf.Timestamp value) {
      if (deliveryTimestampBuilder_ == null) {
        if (deliveryTimestamp_ != null) {
          deliveryTimestamp_ =
            com.google.protobuf.Timestamp.newBuilder(deliveryTimestamp_).mergeFrom(value).buildPartial();
        } else {
          deliveryTimestamp_ = value;
        }
        onChanged();
      } else {
        deliveryTimestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public Builder clearDeliveryTimestamp() {
      if (deliveryTimestampBuilder_ == null) {
        deliveryTimestamp_ = null;
        onChanged();
      } else {
        deliveryTimestamp_ = null;
        deliveryTimestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDeliveryTimestampBuilder() {
      
      onChanged();
      return getDeliveryTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDeliveryTimestampOrBuilder() {
      if (deliveryTimestampBuilder_ != null) {
        return deliveryTimestampBuilder_.getMessageOrBuilder();
      } else {
        return deliveryTimestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : deliveryTimestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp delivery_timestamp = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDeliveryTimestampFieldBuilder() {
      if (deliveryTimestampBuilder_ == null) {
        deliveryTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeliveryTimestamp(),
                getParentForChildren(),
                isClean());
        deliveryTimestamp_ = null;
      }
      return deliveryTimestampBuilder_;
    }

    private com.google.protobuf.Duration invisibleDuration_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> invisibleDurationBuilder_;
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     * @return Whether the invisibleDuration field is set.
     */
    public boolean hasInvisibleDuration() {
      return invisibleDurationBuilder_ != null || invisibleDuration_ != null;
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     * @return The invisibleDuration.
     */
    public com.google.protobuf.Duration getInvisibleDuration() {
      if (invisibleDurationBuilder_ == null) {
        return invisibleDuration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : invisibleDuration_;
      } else {
        return invisibleDurationBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     */
    public Builder setInvisibleDuration(com.google.protobuf.Duration value) {
      if (invisibleDurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        invisibleDuration_ = value;
        onChanged();
      } else {
        invisibleDurationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     */
    public Builder setInvisibleDuration(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (invisibleDurationBuilder_ == null) {
        invisibleDuration_ = builderForValue.build();
        onChanged();
      } else {
        invisibleDurationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     */
    public Builder mergeInvisibleDuration(com.google.protobuf.Duration value) {
      if (invisibleDurationBuilder_ == null) {
        if (invisibleDuration_ != null) {
          invisibleDuration_ =
            com.google.protobuf.Duration.newBuilder(invisibleDuration_).mergeFrom(value).buildPartial();
        } else {
          invisibleDuration_ = value;
        }
        onChanged();
      } else {
        invisibleDurationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     */
    public Builder clearInvisibleDuration() {
      if (invisibleDurationBuilder_ == null) {
        invisibleDuration_ = null;
        onChanged();
      } else {
        invisibleDuration_ = null;
        invisibleDurationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     */
    public com.google.protobuf.Duration.Builder getInvisibleDurationBuilder() {
      
      onChanged();
      return getInvisibleDurationFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     */
    public com.google.protobuf.DurationOrBuilder getInvisibleDurationOrBuilder() {
      if (invisibleDurationBuilder_ != null) {
        return invisibleDurationBuilder_.getMessageOrBuilder();
      } else {
        return invisibleDuration_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : invisibleDuration_;
      }
    }
    /**
     * <code>.google.protobuf.Duration invisible_duration = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getInvisibleDurationFieldBuilder() {
      if (invisibleDurationBuilder_ == null) {
        invisibleDurationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getInvisibleDuration(),
                getParentForChildren(),
                isClean());
        invisibleDuration_ = null;
      }
      return invisibleDurationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.ReceiveMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.ReceiveMessageResponse)
  private static final apache.rocketmq.v2.ReceiveMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.ReceiveMessageResponse();
  }

  public static apache.rocketmq.v2.ReceiveMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReceiveMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReceiveMessageResponse>() {
    @java.lang.Override
    public ReceiveMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReceiveMessageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReceiveMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReceiveMessageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.ReceiveMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

