// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public interface ReceiveMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.ReceiveMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v2.Resource group = 1;</code>
   * @return Whether the group field is set.
   */
  boolean hasGroup();
  /**
   * <code>.apache.rocketmq.v2.Resource group = 1;</code>
   * @return The group.
   */
  apache.rocketmq.v2.Resource getGroup();
  /**
   * <code>.apache.rocketmq.v2.Resource group = 1;</code>
   */
  apache.rocketmq.v2.ResourceOrBuilder getGroupOrBuilder();

  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
   * @return Whether the messageQueue field is set.
   */
  boolean hasMessageQueue();
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
   * @return The messageQueue.
   */
  apache.rocketmq.v2.MessageQueue getMessageQueue();
  /**
   * <code>.apache.rocketmq.v2.MessageQueue message_queue = 2;</code>
   */
  apache.rocketmq.v2.MessageQueueOrBuilder getMessageQueueOrBuilder();

  /**
   * <code>.apache.rocketmq.v2.FilterExpression filter_expression = 3;</code>
   * @return Whether the filterExpression field is set.
   */
  boolean hasFilterExpression();
  /**
   * <code>.apache.rocketmq.v2.FilterExpression filter_expression = 3;</code>
   * @return The filterExpression.
   */
  apache.rocketmq.v2.FilterExpression getFilterExpression();
  /**
   * <code>.apache.rocketmq.v2.FilterExpression filter_expression = 3;</code>
   */
  apache.rocketmq.v2.FilterExpressionOrBuilder getFilterExpressionOrBuilder();

  /**
   * <code>int32 batch_size = 4;</code>
   * @return The batchSize.
   */
  int getBatchSize();

  /**
   * <pre>
   * Required if client type is simple consumer.
   * </pre>
   *
   * <code>optional .google.protobuf.Duration invisible_duration = 5;</code>
   * @return Whether the invisibleDuration field is set.
   */
  boolean hasInvisibleDuration();
  /**
   * <pre>
   * Required if client type is simple consumer.
   * </pre>
   *
   * <code>optional .google.protobuf.Duration invisible_duration = 5;</code>
   * @return The invisibleDuration.
   */
  com.google.protobuf.Duration getInvisibleDuration();
  /**
   * <pre>
   * Required if client type is simple consumer.
   * </pre>
   *
   * <code>optional .google.protobuf.Duration invisible_duration = 5;</code>
   */
  com.google.protobuf.DurationOrBuilder getInvisibleDurationOrBuilder();

  /**
   * <pre>
   * For message auto renew and clean
   * </pre>
   *
   * <code>bool auto_renew = 6;</code>
   * @return The autoRenew.
   */
  boolean getAutoRenew();
}
