// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public interface RecoverOrphanedTransactionCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.RecoverOrphanedTransactionCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 command_id = 1;</code>
   * @return The commandId.
   */
  long getCommandId();

  /**
   * <code>.apache.rocketmq.v2.Message orphaned_transactional_message = 2;</code>
   * @return Whether the orphanedTransactionalMessage field is set.
   */
  boolean hasOrphanedTransactionalMessage();
  /**
   * <code>.apache.rocketmq.v2.Message orphaned_transactional_message = 2;</code>
   * @return The orphanedTransactionalMessage.
   */
  apache.rocketmq.v2.Message getOrphanedTransactionalMessage();
  /**
   * <code>.apache.rocketmq.v2.Message orphaned_transactional_message = 2;</code>
   */
  apache.rocketmq.v2.MessageOrBuilder getOrphanedTransactionalMessageOrBuilder();

  /**
   * <code>string transaction_id = 3;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 3;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();
}
