// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.ReportActiveSettingsCommand}
 */
public final class ReportActiveSettingsCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.ReportActiveSettingsCommand)
    ReportActiveSettingsCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportActiveSettingsCommand.newBuilder() to construct.
  private ReportActiveSettingsCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportActiveSettingsCommand() {
    nonce_ = "";
    clientType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportActiveSettingsCommand();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportActiveSettingsCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            nonce_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            clientType_ = rawValue;
            break;
          }
          case 26: {
            apache.rocketmq.v2.Endpoints.Builder subBuilder = null;
            if (accessPoint_ != null) {
              subBuilder = accessPoint_.toBuilder();
            }
            accessPoint_ = input.readMessage(apache.rocketmq.v2.Endpoints.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(accessPoint_);
              accessPoint_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (connectionTimeout_ != null) {
              subBuilder = connectionTimeout_.toBuilder();
            }
            connectionTimeout_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(connectionTimeout_);
              connectionTimeout_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            traceOn_ = input.readBool();
            break;
          }
          case 50: {
            apache.rocketmq.v2.ActivePublishingSettings.Builder subBuilder = null;
            if (settingsCase_ == 6) {
              subBuilder = ((apache.rocketmq.v2.ActivePublishingSettings) settings_).toBuilder();
            }
            settings_ =
                input.readMessage(apache.rocketmq.v2.ActivePublishingSettings.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.ActivePublishingSettings) settings_);
              settings_ = subBuilder.buildPartial();
            }
            settingsCase_ = 6;
            break;
          }
          case 58: {
            apache.rocketmq.v2.ActiveSubscriptionSettings.Builder subBuilder = null;
            if (settingsCase_ == 7) {
              subBuilder = ((apache.rocketmq.v2.ActiveSubscriptionSettings) settings_).toBuilder();
            }
            settings_ =
                input.readMessage(apache.rocketmq.v2.ActiveSubscriptionSettings.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v2.ActiveSubscriptionSettings) settings_);
              settings_ = subBuilder.buildPartial();
            }
            settingsCase_ = 7;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReportActiveSettingsCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReportActiveSettingsCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.ReportActiveSettingsCommand.class, apache.rocketmq.v2.ReportActiveSettingsCommand.Builder.class);
  }

  private int settingsCase_ = 0;
  private java.lang.Object settings_;
  public enum SettingsCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ACTIVE_PUBLISHING_SETTINGS(6),
    ACTIVE_SUBSCRIPTION_SETTINGS(7),
    SETTINGS_NOT_SET(0);
    private final int value;
    private SettingsCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SettingsCase valueOf(int value) {
      return forNumber(value);
    }

    public static SettingsCase forNumber(int value) {
      switch (value) {
        case 6: return ACTIVE_PUBLISHING_SETTINGS;
        case 7: return ACTIVE_SUBSCRIPTION_SETTINGS;
        case 0: return SETTINGS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SettingsCase
  getSettingsCase() {
    return SettingsCase.forNumber(
        settingsCase_);
  }

  public static final int NONCE_FIELD_NUMBER = 1;
  private volatile java.lang.Object nonce_;
  /**
   * <code>string nonce = 1;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public java.lang.String getNonce() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nonce_ = s;
      return s;
    }
  }
  /**
   * <code>string nonce = 1;</code>
   * @return The bytes for nonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNonceBytes() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonce_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_TYPE_FIELD_NUMBER = 2;
  private int clientType_;
  /**
   * <code>.apache.rocketmq.v2.ClientType client_type = 2;</code>
   * @return The enum numeric value on the wire for clientType.
   */
  @java.lang.Override public int getClientTypeValue() {
    return clientType_;
  }
  /**
   * <code>.apache.rocketmq.v2.ClientType client_type = 2;</code>
   * @return The clientType.
   */
  @java.lang.Override public apache.rocketmq.v2.ClientType getClientType() {
    @SuppressWarnings("deprecation")
    apache.rocketmq.v2.ClientType result = apache.rocketmq.v2.ClientType.valueOf(clientType_);
    return result == null ? apache.rocketmq.v2.ClientType.UNRECOGNIZED : result;
  }

  public static final int ACCESS_POINT_FIELD_NUMBER = 3;
  private apache.rocketmq.v2.Endpoints accessPoint_;
  /**
   * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
   * @return Whether the accessPoint field is set.
   */
  @java.lang.Override
  public boolean hasAccessPoint() {
    return accessPoint_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
   * @return The accessPoint.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Endpoints getAccessPoint() {
    return accessPoint_ == null ? apache.rocketmq.v2.Endpoints.getDefaultInstance() : accessPoint_;
  }
  /**
   * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.EndpointsOrBuilder getAccessPointOrBuilder() {
    return getAccessPoint();
  }

  public static final int CONNECTION_TIMEOUT_FIELD_NUMBER = 4;
  private com.google.protobuf.Duration connectionTimeout_;
  /**
   * <code>.google.protobuf.Duration connection_timeout = 4;</code>
   * @return Whether the connectionTimeout field is set.
   */
  @java.lang.Override
  public boolean hasConnectionTimeout() {
    return connectionTimeout_ != null;
  }
  /**
   * <code>.google.protobuf.Duration connection_timeout = 4;</code>
   * @return The connectionTimeout.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getConnectionTimeout() {
    return connectionTimeout_ == null ? com.google.protobuf.Duration.getDefaultInstance() : connectionTimeout_;
  }
  /**
   * <code>.google.protobuf.Duration connection_timeout = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getConnectionTimeoutOrBuilder() {
    return getConnectionTimeout();
  }

  public static final int TRACE_ON_FIELD_NUMBER = 5;
  private boolean traceOn_;
  /**
   * <code>bool trace_on = 5;</code>
   * @return The traceOn.
   */
  @java.lang.Override
  public boolean getTraceOn() {
    return traceOn_;
  }

  public static final int ACTIVE_PUBLISHING_SETTINGS_FIELD_NUMBER = 6;
  /**
   * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
   * @return Whether the activePublishingSettings field is set.
   */
  @java.lang.Override
  public boolean hasActivePublishingSettings() {
    return settingsCase_ == 6;
  }
  /**
   * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
   * @return The activePublishingSettings.
   */
  @java.lang.Override
  public apache.rocketmq.v2.ActivePublishingSettings getActivePublishingSettings() {
    if (settingsCase_ == 6) {
       return (apache.rocketmq.v2.ActivePublishingSettings) settings_;
    }
    return apache.rocketmq.v2.ActivePublishingSettings.getDefaultInstance();
  }
  /**
   * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.ActivePublishingSettingsOrBuilder getActivePublishingSettingsOrBuilder() {
    if (settingsCase_ == 6) {
       return (apache.rocketmq.v2.ActivePublishingSettings) settings_;
    }
    return apache.rocketmq.v2.ActivePublishingSettings.getDefaultInstance();
  }

  public static final int ACTIVE_SUBSCRIPTION_SETTINGS_FIELD_NUMBER = 7;
  /**
   * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
   * @return Whether the activeSubscriptionSettings field is set.
   */
  @java.lang.Override
  public boolean hasActiveSubscriptionSettings() {
    return settingsCase_ == 7;
  }
  /**
   * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
   * @return The activeSubscriptionSettings.
   */
  @java.lang.Override
  public apache.rocketmq.v2.ActiveSubscriptionSettings getActiveSubscriptionSettings() {
    if (settingsCase_ == 7) {
       return (apache.rocketmq.v2.ActiveSubscriptionSettings) settings_;
    }
    return apache.rocketmq.v2.ActiveSubscriptionSettings.getDefaultInstance();
  }
  /**
   * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.ActiveSubscriptionSettingsOrBuilder getActiveSubscriptionSettingsOrBuilder() {
    if (settingsCase_ == 7) {
       return (apache.rocketmq.v2.ActiveSubscriptionSettings) settings_;
    }
    return apache.rocketmq.v2.ActiveSubscriptionSettings.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonce_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nonce_);
    }
    if (clientType_ != apache.rocketmq.v2.ClientType.CLIENT_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, clientType_);
    }
    if (accessPoint_ != null) {
      output.writeMessage(3, getAccessPoint());
    }
    if (connectionTimeout_ != null) {
      output.writeMessage(4, getConnectionTimeout());
    }
    if (traceOn_ != false) {
      output.writeBool(5, traceOn_);
    }
    if (settingsCase_ == 6) {
      output.writeMessage(6, (apache.rocketmq.v2.ActivePublishingSettings) settings_);
    }
    if (settingsCase_ == 7) {
      output.writeMessage(7, (apache.rocketmq.v2.ActiveSubscriptionSettings) settings_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonce_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nonce_);
    }
    if (clientType_ != apache.rocketmq.v2.ClientType.CLIENT_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, clientType_);
    }
    if (accessPoint_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAccessPoint());
    }
    if (connectionTimeout_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getConnectionTimeout());
    }
    if (traceOn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, traceOn_);
    }
    if (settingsCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (apache.rocketmq.v2.ActivePublishingSettings) settings_);
    }
    if (settingsCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (apache.rocketmq.v2.ActiveSubscriptionSettings) settings_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.ReportActiveSettingsCommand)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.ReportActiveSettingsCommand other = (apache.rocketmq.v2.ReportActiveSettingsCommand) obj;

    if (!getNonce()
        .equals(other.getNonce())) return false;
    if (clientType_ != other.clientType_) return false;
    if (hasAccessPoint() != other.hasAccessPoint()) return false;
    if (hasAccessPoint()) {
      if (!getAccessPoint()
          .equals(other.getAccessPoint())) return false;
    }
    if (hasConnectionTimeout() != other.hasConnectionTimeout()) return false;
    if (hasConnectionTimeout()) {
      if (!getConnectionTimeout()
          .equals(other.getConnectionTimeout())) return false;
    }
    if (getTraceOn()
        != other.getTraceOn()) return false;
    if (!getSettingsCase().equals(other.getSettingsCase())) return false;
    switch (settingsCase_) {
      case 6:
        if (!getActivePublishingSettings()
            .equals(other.getActivePublishingSettings())) return false;
        break;
      case 7:
        if (!getActiveSubscriptionSettings()
            .equals(other.getActiveSubscriptionSettings())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getNonce().hashCode();
    hash = (37 * hash) + CLIENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + clientType_;
    if (hasAccessPoint()) {
      hash = (37 * hash) + ACCESS_POINT_FIELD_NUMBER;
      hash = (53 * hash) + getAccessPoint().hashCode();
    }
    if (hasConnectionTimeout()) {
      hash = (37 * hash) + CONNECTION_TIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + getConnectionTimeout().hashCode();
    }
    hash = (37 * hash) + TRACE_ON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTraceOn());
    switch (settingsCase_) {
      case 6:
        hash = (37 * hash) + ACTIVE_PUBLISHING_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getActivePublishingSettings().hashCode();
        break;
      case 7:
        hash = (37 * hash) + ACTIVE_SUBSCRIPTION_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getActiveSubscriptionSettings().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.ReportActiveSettingsCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.ReportActiveSettingsCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.ReportActiveSettingsCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.ReportActiveSettingsCommand)
      apache.rocketmq.v2.ReportActiveSettingsCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReportActiveSettingsCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReportActiveSettingsCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.ReportActiveSettingsCommand.class, apache.rocketmq.v2.ReportActiveSettingsCommand.Builder.class);
    }

    // Construct using apache.rocketmq.v2.ReportActiveSettingsCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nonce_ = "";

      clientType_ = 0;

      if (accessPointBuilder_ == null) {
        accessPoint_ = null;
      } else {
        accessPoint_ = null;
        accessPointBuilder_ = null;
      }
      if (connectionTimeoutBuilder_ == null) {
        connectionTimeout_ = null;
      } else {
        connectionTimeout_ = null;
        connectionTimeoutBuilder_ = null;
      }
      traceOn_ = false;

      settingsCase_ = 0;
      settings_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQService.internal_static_apache_rocketmq_v2_ReportActiveSettingsCommand_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReportActiveSettingsCommand getDefaultInstanceForType() {
      return apache.rocketmq.v2.ReportActiveSettingsCommand.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReportActiveSettingsCommand build() {
      apache.rocketmq.v2.ReportActiveSettingsCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.ReportActiveSettingsCommand buildPartial() {
      apache.rocketmq.v2.ReportActiveSettingsCommand result = new apache.rocketmq.v2.ReportActiveSettingsCommand(this);
      result.nonce_ = nonce_;
      result.clientType_ = clientType_;
      if (accessPointBuilder_ == null) {
        result.accessPoint_ = accessPoint_;
      } else {
        result.accessPoint_ = accessPointBuilder_.build();
      }
      if (connectionTimeoutBuilder_ == null) {
        result.connectionTimeout_ = connectionTimeout_;
      } else {
        result.connectionTimeout_ = connectionTimeoutBuilder_.build();
      }
      result.traceOn_ = traceOn_;
      if (settingsCase_ == 6) {
        if (activePublishingSettingsBuilder_ == null) {
          result.settings_ = settings_;
        } else {
          result.settings_ = activePublishingSettingsBuilder_.build();
        }
      }
      if (settingsCase_ == 7) {
        if (activeSubscriptionSettingsBuilder_ == null) {
          result.settings_ = settings_;
        } else {
          result.settings_ = activeSubscriptionSettingsBuilder_.build();
        }
      }
      result.settingsCase_ = settingsCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.ReportActiveSettingsCommand) {
        return mergeFrom((apache.rocketmq.v2.ReportActiveSettingsCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.ReportActiveSettingsCommand other) {
      if (other == apache.rocketmq.v2.ReportActiveSettingsCommand.getDefaultInstance()) return this;
      if (!other.getNonce().isEmpty()) {
        nonce_ = other.nonce_;
        onChanged();
      }
      if (other.clientType_ != 0) {
        setClientTypeValue(other.getClientTypeValue());
      }
      if (other.hasAccessPoint()) {
        mergeAccessPoint(other.getAccessPoint());
      }
      if (other.hasConnectionTimeout()) {
        mergeConnectionTimeout(other.getConnectionTimeout());
      }
      if (other.getTraceOn() != false) {
        setTraceOn(other.getTraceOn());
      }
      switch (other.getSettingsCase()) {
        case ACTIVE_PUBLISHING_SETTINGS: {
          mergeActivePublishingSettings(other.getActivePublishingSettings());
          break;
        }
        case ACTIVE_SUBSCRIPTION_SETTINGS: {
          mergeActiveSubscriptionSettings(other.getActiveSubscriptionSettings());
          break;
        }
        case SETTINGS_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.ReportActiveSettingsCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.ReportActiveSettingsCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int settingsCase_ = 0;
    private java.lang.Object settings_;
    public SettingsCase
        getSettingsCase() {
      return SettingsCase.forNumber(
          settingsCase_);
    }

    public Builder clearSettings() {
      settingsCase_ = 0;
      settings_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object nonce_ = "";
    /**
     * <code>string nonce = 1;</code>
     * @return The nonce.
     */
    public java.lang.String getNonce() {
      java.lang.Object ref = nonce_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nonce_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nonce = 1;</code>
     * @return The bytes for nonce.
     */
    public com.google.protobuf.ByteString
        getNonceBytes() {
      java.lang.Object ref = nonce_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonce_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nonce = 1;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nonce = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }
    /**
     * <code>string nonce = 1;</code>
     * @param value The bytes for nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nonce_ = value;
      onChanged();
      return this;
    }

    private int clientType_ = 0;
    /**
     * <code>.apache.rocketmq.v2.ClientType client_type = 2;</code>
     * @return The enum numeric value on the wire for clientType.
     */
    @java.lang.Override public int getClientTypeValue() {
      return clientType_;
    }
    /**
     * <code>.apache.rocketmq.v2.ClientType client_type = 2;</code>
     * @param value The enum numeric value on the wire for clientType to set.
     * @return This builder for chaining.
     */
    public Builder setClientTypeValue(int value) {
      
      clientType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ClientType client_type = 2;</code>
     * @return The clientType.
     */
    @java.lang.Override
    public apache.rocketmq.v2.ClientType getClientType() {
      @SuppressWarnings("deprecation")
      apache.rocketmq.v2.ClientType result = apache.rocketmq.v2.ClientType.valueOf(clientType_);
      return result == null ? apache.rocketmq.v2.ClientType.UNRECOGNIZED : result;
    }
    /**
     * <code>.apache.rocketmq.v2.ClientType client_type = 2;</code>
     * @param value The clientType to set.
     * @return This builder for chaining.
     */
    public Builder setClientType(apache.rocketmq.v2.ClientType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      clientType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ClientType client_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientType() {
      
      clientType_ = 0;
      onChanged();
      return this;
    }

    private apache.rocketmq.v2.Endpoints accessPoint_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Endpoints, apache.rocketmq.v2.Endpoints.Builder, apache.rocketmq.v2.EndpointsOrBuilder> accessPointBuilder_;
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     * @return Whether the accessPoint field is set.
     */
    public boolean hasAccessPoint() {
      return accessPointBuilder_ != null || accessPoint_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     * @return The accessPoint.
     */
    public apache.rocketmq.v2.Endpoints getAccessPoint() {
      if (accessPointBuilder_ == null) {
        return accessPoint_ == null ? apache.rocketmq.v2.Endpoints.getDefaultInstance() : accessPoint_;
      } else {
        return accessPointBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     */
    public Builder setAccessPoint(apache.rocketmq.v2.Endpoints value) {
      if (accessPointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accessPoint_ = value;
        onChanged();
      } else {
        accessPointBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     */
    public Builder setAccessPoint(
        apache.rocketmq.v2.Endpoints.Builder builderForValue) {
      if (accessPointBuilder_ == null) {
        accessPoint_ = builderForValue.build();
        onChanged();
      } else {
        accessPointBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     */
    public Builder mergeAccessPoint(apache.rocketmq.v2.Endpoints value) {
      if (accessPointBuilder_ == null) {
        if (accessPoint_ != null) {
          accessPoint_ =
            apache.rocketmq.v2.Endpoints.newBuilder(accessPoint_).mergeFrom(value).buildPartial();
        } else {
          accessPoint_ = value;
        }
        onChanged();
      } else {
        accessPointBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     */
    public Builder clearAccessPoint() {
      if (accessPointBuilder_ == null) {
        accessPoint_ = null;
        onChanged();
      } else {
        accessPoint_ = null;
        accessPointBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     */
    public apache.rocketmq.v2.Endpoints.Builder getAccessPointBuilder() {
      
      onChanged();
      return getAccessPointFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     */
    public apache.rocketmq.v2.EndpointsOrBuilder getAccessPointOrBuilder() {
      if (accessPointBuilder_ != null) {
        return accessPointBuilder_.getMessageOrBuilder();
      } else {
        return accessPoint_ == null ?
            apache.rocketmq.v2.Endpoints.getDefaultInstance() : accessPoint_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints access_point = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Endpoints, apache.rocketmq.v2.Endpoints.Builder, apache.rocketmq.v2.EndpointsOrBuilder> 
        getAccessPointFieldBuilder() {
      if (accessPointBuilder_ == null) {
        accessPointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Endpoints, apache.rocketmq.v2.Endpoints.Builder, apache.rocketmq.v2.EndpointsOrBuilder>(
                getAccessPoint(),
                getParentForChildren(),
                isClean());
        accessPoint_ = null;
      }
      return accessPointBuilder_;
    }

    private com.google.protobuf.Duration connectionTimeout_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> connectionTimeoutBuilder_;
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     * @return Whether the connectionTimeout field is set.
     */
    public boolean hasConnectionTimeout() {
      return connectionTimeoutBuilder_ != null || connectionTimeout_ != null;
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     * @return The connectionTimeout.
     */
    public com.google.protobuf.Duration getConnectionTimeout() {
      if (connectionTimeoutBuilder_ == null) {
        return connectionTimeout_ == null ? com.google.protobuf.Duration.getDefaultInstance() : connectionTimeout_;
      } else {
        return connectionTimeoutBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     */
    public Builder setConnectionTimeout(com.google.protobuf.Duration value) {
      if (connectionTimeoutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        connectionTimeout_ = value;
        onChanged();
      } else {
        connectionTimeoutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     */
    public Builder setConnectionTimeout(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (connectionTimeoutBuilder_ == null) {
        connectionTimeout_ = builderForValue.build();
        onChanged();
      } else {
        connectionTimeoutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     */
    public Builder mergeConnectionTimeout(com.google.protobuf.Duration value) {
      if (connectionTimeoutBuilder_ == null) {
        if (connectionTimeout_ != null) {
          connectionTimeout_ =
            com.google.protobuf.Duration.newBuilder(connectionTimeout_).mergeFrom(value).buildPartial();
        } else {
          connectionTimeout_ = value;
        }
        onChanged();
      } else {
        connectionTimeoutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     */
    public Builder clearConnectionTimeout() {
      if (connectionTimeoutBuilder_ == null) {
        connectionTimeout_ = null;
        onChanged();
      } else {
        connectionTimeout_ = null;
        connectionTimeoutBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     */
    public com.google.protobuf.Duration.Builder getConnectionTimeoutBuilder() {
      
      onChanged();
      return getConnectionTimeoutFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     */
    public com.google.protobuf.DurationOrBuilder getConnectionTimeoutOrBuilder() {
      if (connectionTimeoutBuilder_ != null) {
        return connectionTimeoutBuilder_.getMessageOrBuilder();
      } else {
        return connectionTimeout_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : connectionTimeout_;
      }
    }
    /**
     * <code>.google.protobuf.Duration connection_timeout = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getConnectionTimeoutFieldBuilder() {
      if (connectionTimeoutBuilder_ == null) {
        connectionTimeoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getConnectionTimeout(),
                getParentForChildren(),
                isClean());
        connectionTimeout_ = null;
      }
      return connectionTimeoutBuilder_;
    }

    private boolean traceOn_ ;
    /**
     * <code>bool trace_on = 5;</code>
     * @return The traceOn.
     */
    @java.lang.Override
    public boolean getTraceOn() {
      return traceOn_;
    }
    /**
     * <code>bool trace_on = 5;</code>
     * @param value The traceOn to set.
     * @return This builder for chaining.
     */
    public Builder setTraceOn(boolean value) {
      
      traceOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool trace_on = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceOn() {
      
      traceOn_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ActivePublishingSettings, apache.rocketmq.v2.ActivePublishingSettings.Builder, apache.rocketmq.v2.ActivePublishingSettingsOrBuilder> activePublishingSettingsBuilder_;
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     * @return Whether the activePublishingSettings field is set.
     */
    @java.lang.Override
    public boolean hasActivePublishingSettings() {
      return settingsCase_ == 6;
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     * @return The activePublishingSettings.
     */
    @java.lang.Override
    public apache.rocketmq.v2.ActivePublishingSettings getActivePublishingSettings() {
      if (activePublishingSettingsBuilder_ == null) {
        if (settingsCase_ == 6) {
          return (apache.rocketmq.v2.ActivePublishingSettings) settings_;
        }
        return apache.rocketmq.v2.ActivePublishingSettings.getDefaultInstance();
      } else {
        if (settingsCase_ == 6) {
          return activePublishingSettingsBuilder_.getMessage();
        }
        return apache.rocketmq.v2.ActivePublishingSettings.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     */
    public Builder setActivePublishingSettings(apache.rocketmq.v2.ActivePublishingSettings value) {
      if (activePublishingSettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settings_ = value;
        onChanged();
      } else {
        activePublishingSettingsBuilder_.setMessage(value);
      }
      settingsCase_ = 6;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     */
    public Builder setActivePublishingSettings(
        apache.rocketmq.v2.ActivePublishingSettings.Builder builderForValue) {
      if (activePublishingSettingsBuilder_ == null) {
        settings_ = builderForValue.build();
        onChanged();
      } else {
        activePublishingSettingsBuilder_.setMessage(builderForValue.build());
      }
      settingsCase_ = 6;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     */
    public Builder mergeActivePublishingSettings(apache.rocketmq.v2.ActivePublishingSettings value) {
      if (activePublishingSettingsBuilder_ == null) {
        if (settingsCase_ == 6 &&
            settings_ != apache.rocketmq.v2.ActivePublishingSettings.getDefaultInstance()) {
          settings_ = apache.rocketmq.v2.ActivePublishingSettings.newBuilder((apache.rocketmq.v2.ActivePublishingSettings) settings_)
              .mergeFrom(value).buildPartial();
        } else {
          settings_ = value;
        }
        onChanged();
      } else {
        if (settingsCase_ == 6) {
          activePublishingSettingsBuilder_.mergeFrom(value);
        }
        activePublishingSettingsBuilder_.setMessage(value);
      }
      settingsCase_ = 6;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     */
    public Builder clearActivePublishingSettings() {
      if (activePublishingSettingsBuilder_ == null) {
        if (settingsCase_ == 6) {
          settingsCase_ = 0;
          settings_ = null;
          onChanged();
        }
      } else {
        if (settingsCase_ == 6) {
          settingsCase_ = 0;
          settings_ = null;
        }
        activePublishingSettingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     */
    public apache.rocketmq.v2.ActivePublishingSettings.Builder getActivePublishingSettingsBuilder() {
      return getActivePublishingSettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.ActivePublishingSettingsOrBuilder getActivePublishingSettingsOrBuilder() {
      if ((settingsCase_ == 6) && (activePublishingSettingsBuilder_ != null)) {
        return activePublishingSettingsBuilder_.getMessageOrBuilder();
      } else {
        if (settingsCase_ == 6) {
          return (apache.rocketmq.v2.ActivePublishingSettings) settings_;
        }
        return apache.rocketmq.v2.ActivePublishingSettings.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.ActivePublishingSettings active_publishing_settings = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ActivePublishingSettings, apache.rocketmq.v2.ActivePublishingSettings.Builder, apache.rocketmq.v2.ActivePublishingSettingsOrBuilder> 
        getActivePublishingSettingsFieldBuilder() {
      if (activePublishingSettingsBuilder_ == null) {
        if (!(settingsCase_ == 6)) {
          settings_ = apache.rocketmq.v2.ActivePublishingSettings.getDefaultInstance();
        }
        activePublishingSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.ActivePublishingSettings, apache.rocketmq.v2.ActivePublishingSettings.Builder, apache.rocketmq.v2.ActivePublishingSettingsOrBuilder>(
                (apache.rocketmq.v2.ActivePublishingSettings) settings_,
                getParentForChildren(),
                isClean());
        settings_ = null;
      }
      settingsCase_ = 6;
      onChanged();;
      return activePublishingSettingsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ActiveSubscriptionSettings, apache.rocketmq.v2.ActiveSubscriptionSettings.Builder, apache.rocketmq.v2.ActiveSubscriptionSettingsOrBuilder> activeSubscriptionSettingsBuilder_;
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     * @return Whether the activeSubscriptionSettings field is set.
     */
    @java.lang.Override
    public boolean hasActiveSubscriptionSettings() {
      return settingsCase_ == 7;
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     * @return The activeSubscriptionSettings.
     */
    @java.lang.Override
    public apache.rocketmq.v2.ActiveSubscriptionSettings getActiveSubscriptionSettings() {
      if (activeSubscriptionSettingsBuilder_ == null) {
        if (settingsCase_ == 7) {
          return (apache.rocketmq.v2.ActiveSubscriptionSettings) settings_;
        }
        return apache.rocketmq.v2.ActiveSubscriptionSettings.getDefaultInstance();
      } else {
        if (settingsCase_ == 7) {
          return activeSubscriptionSettingsBuilder_.getMessage();
        }
        return apache.rocketmq.v2.ActiveSubscriptionSettings.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     */
    public Builder setActiveSubscriptionSettings(apache.rocketmq.v2.ActiveSubscriptionSettings value) {
      if (activeSubscriptionSettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settings_ = value;
        onChanged();
      } else {
        activeSubscriptionSettingsBuilder_.setMessage(value);
      }
      settingsCase_ = 7;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     */
    public Builder setActiveSubscriptionSettings(
        apache.rocketmq.v2.ActiveSubscriptionSettings.Builder builderForValue) {
      if (activeSubscriptionSettingsBuilder_ == null) {
        settings_ = builderForValue.build();
        onChanged();
      } else {
        activeSubscriptionSettingsBuilder_.setMessage(builderForValue.build());
      }
      settingsCase_ = 7;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     */
    public Builder mergeActiveSubscriptionSettings(apache.rocketmq.v2.ActiveSubscriptionSettings value) {
      if (activeSubscriptionSettingsBuilder_ == null) {
        if (settingsCase_ == 7 &&
            settings_ != apache.rocketmq.v2.ActiveSubscriptionSettings.getDefaultInstance()) {
          settings_ = apache.rocketmq.v2.ActiveSubscriptionSettings.newBuilder((apache.rocketmq.v2.ActiveSubscriptionSettings) settings_)
              .mergeFrom(value).buildPartial();
        } else {
          settings_ = value;
        }
        onChanged();
      } else {
        if (settingsCase_ == 7) {
          activeSubscriptionSettingsBuilder_.mergeFrom(value);
        }
        activeSubscriptionSettingsBuilder_.setMessage(value);
      }
      settingsCase_ = 7;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     */
    public Builder clearActiveSubscriptionSettings() {
      if (activeSubscriptionSettingsBuilder_ == null) {
        if (settingsCase_ == 7) {
          settingsCase_ = 0;
          settings_ = null;
          onChanged();
        }
      } else {
        if (settingsCase_ == 7) {
          settingsCase_ = 0;
          settings_ = null;
        }
        activeSubscriptionSettingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     */
    public apache.rocketmq.v2.ActiveSubscriptionSettings.Builder getActiveSubscriptionSettingsBuilder() {
      return getActiveSubscriptionSettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v2.ActiveSubscriptionSettingsOrBuilder getActiveSubscriptionSettingsOrBuilder() {
      if ((settingsCase_ == 7) && (activeSubscriptionSettingsBuilder_ != null)) {
        return activeSubscriptionSettingsBuilder_.getMessageOrBuilder();
      } else {
        if (settingsCase_ == 7) {
          return (apache.rocketmq.v2.ActiveSubscriptionSettings) settings_;
        }
        return apache.rocketmq.v2.ActiveSubscriptionSettings.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.ActiveSubscriptionSettings active_subscription_settings = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.ActiveSubscriptionSettings, apache.rocketmq.v2.ActiveSubscriptionSettings.Builder, apache.rocketmq.v2.ActiveSubscriptionSettingsOrBuilder> 
        getActiveSubscriptionSettingsFieldBuilder() {
      if (activeSubscriptionSettingsBuilder_ == null) {
        if (!(settingsCase_ == 7)) {
          settings_ = apache.rocketmq.v2.ActiveSubscriptionSettings.getDefaultInstance();
        }
        activeSubscriptionSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.ActiveSubscriptionSettings, apache.rocketmq.v2.ActiveSubscriptionSettings.Builder, apache.rocketmq.v2.ActiveSubscriptionSettingsOrBuilder>(
                (apache.rocketmq.v2.ActiveSubscriptionSettings) settings_,
                getParentForChildren(),
                isClean());
        settings_ = null;
      }
      settingsCase_ = 7;
      onChanged();;
      return activeSubscriptionSettingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.ReportActiveSettingsCommand)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.ReportActiveSettingsCommand)
  private static final apache.rocketmq.v2.ReportActiveSettingsCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.ReportActiveSettingsCommand();
  }

  public static apache.rocketmq.v2.ReportActiveSettingsCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportActiveSettingsCommand>
      PARSER = new com.google.protobuf.AbstractParser<ReportActiveSettingsCommand>() {
    @java.lang.Override
    public ReportActiveSettingsCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportActiveSettingsCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportActiveSettingsCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportActiveSettingsCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.ReportActiveSettingsCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

