// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public interface SettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.Settings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .apache.rocketmq.v2.Publishing publishing = 1;</code>
   * @return Whether the publishing field is set.
   */
  boolean hasPublishing();
  /**
   * <code>optional .apache.rocketmq.v2.Publishing publishing = 1;</code>
   * @return The publishing.
   */
  apache.rocketmq.v2.Publishing getPublishing();
  /**
   * <code>optional .apache.rocketmq.v2.Publishing publishing = 1;</code>
   */
  apache.rocketmq.v2.PublishingOrBuilder getPublishingOrBuilder();

  /**
   * <code>optional .apache.rocketmq.v2.Subscription subscription = 2;</code>
   * @return Whether the subscription field is set.
   */
  boolean hasSubscription();
  /**
   * <code>optional .apache.rocketmq.v2.Subscription subscription = 2;</code>
   * @return The subscription.
   */
  apache.rocketmq.v2.Subscription getSubscription();
  /**
   * <code>optional .apache.rocketmq.v2.Subscription subscription = 2;</code>
   */
  apache.rocketmq.v2.SubscriptionOrBuilder getSubscriptionOrBuilder();

  /**
   * <code>.apache.rocketmq.v2.Tracing tracing = 3;</code>
   * @return Whether the tracing field is set.
   */
  boolean hasTracing();
  /**
   * <code>.apache.rocketmq.v2.Tracing tracing = 3;</code>
   * @return The tracing.
   */
  apache.rocketmq.v2.Tracing getTracing();
  /**
   * <code>.apache.rocketmq.v2.Tracing tracing = 3;</code>
   */
  apache.rocketmq.v2.TracingOrBuilder getTracingOrBuilder();
}
