// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/definition.proto

package apache.rocketmq.v2;

public interface TimeoutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.Timeout)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Duration connect = 1;</code>
   * @return Whether the connect field is set.
   */
  boolean hasConnect();
  /**
   * <code>.google.protobuf.Duration connect = 1;</code>
   * @return The connect.
   */
  com.google.protobuf.Duration getConnect();
  /**
   * <code>.google.protobuf.Duration connect = 1;</code>
   */
  com.google.protobuf.DurationOrBuilder getConnectOrBuilder();

  /**
   * <code>.google.protobuf.Duration request = 2;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.google.protobuf.Duration request = 2;</code>
   * @return The request.
   */
  com.google.protobuf.Duration getRequest();
  /**
   * <code>.google.protobuf.Duration request = 2;</code>
   */
  com.google.protobuf.DurationOrBuilder getRequestOrBuilder();

  /**
   * <pre>
   * Long polling duration
   * </pre>
   *
   * <code>.google.protobuf.Duration polling = 3;</code>
   * @return Whether the polling field is set.
   */
  boolean hasPolling();
  /**
   * <pre>
   * Long polling duration
   * </pre>
   *
   * <code>.google.protobuf.Duration polling = 3;</code>
   * @return The polling.
   */
  com.google.protobuf.Duration getPolling();
  /**
   * <pre>
   * Long polling duration
   * </pre>
   *
   * <code>.google.protobuf.Duration polling = 3;</code>
   */
  com.google.protobuf.DurationOrBuilder getPollingOrBuilder();
}
