// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/definition.proto

package apache.rocketmq.v2;

public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool on = 1;</code>
   * @return The on.
   */
  boolean getOn();

  /**
   * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
   * @return Whether the serviceAccessPoint field is set.
   */
  boolean hasServiceAccessPoint();
  /**
   * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
   * @return The serviceAccessPoint.
   */
  apache.rocketmq.v2.Endpoints getServiceAccessPoint();
  /**
   * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
   */
  apache.rocketmq.v2.EndpointsOrBuilder getServiceAccessPointOrBuilder();
}
