// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/definition.proto

package apache.rocketmq.v2;

/**
 * Protobuf type {@code apache.rocketmq.v2.Trace}
 */
public final class Trace extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v2.Trace)
    TraceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Trace.newBuilder() to construct.
  private Trace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Trace() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Trace();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Trace(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            on_ = input.readBool();
            break;
          }
          case 18: {
            apache.rocketmq.v2.Endpoints.Builder subBuilder = null;
            if (serviceAccessPoint_ != null) {
              subBuilder = serviceAccessPoint_.toBuilder();
            }
            serviceAccessPoint_ = input.readMessage(apache.rocketmq.v2.Endpoints.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(serviceAccessPoint_);
              serviceAccessPoint_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Trace_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Trace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v2.Trace.class, apache.rocketmq.v2.Trace.Builder.class);
  }

  public static final int ON_FIELD_NUMBER = 1;
  private boolean on_;
  /**
   * <code>bool on = 1;</code>
   * @return The on.
   */
  @java.lang.Override
  public boolean getOn() {
    return on_;
  }

  public static final int SERVICE_ACCESS_POINT_FIELD_NUMBER = 2;
  private apache.rocketmq.v2.Endpoints serviceAccessPoint_;
  /**
   * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
   * @return Whether the serviceAccessPoint field is set.
   */
  @java.lang.Override
  public boolean hasServiceAccessPoint() {
    return serviceAccessPoint_ != null;
  }
  /**
   * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
   * @return The serviceAccessPoint.
   */
  @java.lang.Override
  public apache.rocketmq.v2.Endpoints getServiceAccessPoint() {
    return serviceAccessPoint_ == null ? apache.rocketmq.v2.Endpoints.getDefaultInstance() : serviceAccessPoint_;
  }
  /**
   * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v2.EndpointsOrBuilder getServiceAccessPointOrBuilder() {
    return getServiceAccessPoint();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (on_ != false) {
      output.writeBool(1, on_);
    }
    if (serviceAccessPoint_ != null) {
      output.writeMessage(2, getServiceAccessPoint());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (on_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, on_);
    }
    if (serviceAccessPoint_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getServiceAccessPoint());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v2.Trace)) {
      return super.equals(obj);
    }
    apache.rocketmq.v2.Trace other = (apache.rocketmq.v2.Trace) obj;

    if (getOn()
        != other.getOn()) return false;
    if (hasServiceAccessPoint() != other.hasServiceAccessPoint()) return false;
    if (hasServiceAccessPoint()) {
      if (!getServiceAccessPoint()
          .equals(other.getServiceAccessPoint())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOn());
    if (hasServiceAccessPoint()) {
      hash = (37 * hash) + SERVICE_ACCESS_POINT_FIELD_NUMBER;
      hash = (53 * hash) + getServiceAccessPoint().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v2.Trace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.Trace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.Trace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.Trace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.Trace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v2.Trace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v2.Trace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.Trace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.Trace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.Trace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v2.Trace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v2.Trace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v2.Trace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v2.Trace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v2.Trace)
      apache.rocketmq.v2.TraceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Trace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Trace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v2.Trace.class, apache.rocketmq.v2.Trace.Builder.class);
    }

    // Construct using apache.rocketmq.v2.Trace.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      on_ = false;

      if (serviceAccessPointBuilder_ == null) {
        serviceAccessPoint_ = null;
      } else {
        serviceAccessPoint_ = null;
        serviceAccessPointBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v2.MQDomain.internal_static_apache_rocketmq_v2_Trace_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v2.Trace getDefaultInstanceForType() {
      return apache.rocketmq.v2.Trace.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v2.Trace build() {
      apache.rocketmq.v2.Trace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v2.Trace buildPartial() {
      apache.rocketmq.v2.Trace result = new apache.rocketmq.v2.Trace(this);
      result.on_ = on_;
      if (serviceAccessPointBuilder_ == null) {
        result.serviceAccessPoint_ = serviceAccessPoint_;
      } else {
        result.serviceAccessPoint_ = serviceAccessPointBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v2.Trace) {
        return mergeFrom((apache.rocketmq.v2.Trace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v2.Trace other) {
      if (other == apache.rocketmq.v2.Trace.getDefaultInstance()) return this;
      if (other.getOn() != false) {
        setOn(other.getOn());
      }
      if (other.hasServiceAccessPoint()) {
        mergeServiceAccessPoint(other.getServiceAccessPoint());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v2.Trace parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v2.Trace) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean on_ ;
    /**
     * <code>bool on = 1;</code>
     * @return The on.
     */
    @java.lang.Override
    public boolean getOn() {
      return on_;
    }
    /**
     * <code>bool on = 1;</code>
     * @param value The on to set.
     * @return This builder for chaining.
     */
    public Builder setOn(boolean value) {
      
      on_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool on = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOn() {
      
      on_ = false;
      onChanged();
      return this;
    }

    private apache.rocketmq.v2.Endpoints serviceAccessPoint_;
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Endpoints, apache.rocketmq.v2.Endpoints.Builder, apache.rocketmq.v2.EndpointsOrBuilder> serviceAccessPointBuilder_;
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     * @return Whether the serviceAccessPoint field is set.
     */
    public boolean hasServiceAccessPoint() {
      return serviceAccessPointBuilder_ != null || serviceAccessPoint_ != null;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     * @return The serviceAccessPoint.
     */
    public apache.rocketmq.v2.Endpoints getServiceAccessPoint() {
      if (serviceAccessPointBuilder_ == null) {
        return serviceAccessPoint_ == null ? apache.rocketmq.v2.Endpoints.getDefaultInstance() : serviceAccessPoint_;
      } else {
        return serviceAccessPointBuilder_.getMessage();
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     */
    public Builder setServiceAccessPoint(apache.rocketmq.v2.Endpoints value) {
      if (serviceAccessPointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serviceAccessPoint_ = value;
        onChanged();
      } else {
        serviceAccessPointBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     */
    public Builder setServiceAccessPoint(
        apache.rocketmq.v2.Endpoints.Builder builderForValue) {
      if (serviceAccessPointBuilder_ == null) {
        serviceAccessPoint_ = builderForValue.build();
        onChanged();
      } else {
        serviceAccessPointBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     */
    public Builder mergeServiceAccessPoint(apache.rocketmq.v2.Endpoints value) {
      if (serviceAccessPointBuilder_ == null) {
        if (serviceAccessPoint_ != null) {
          serviceAccessPoint_ =
            apache.rocketmq.v2.Endpoints.newBuilder(serviceAccessPoint_).mergeFrom(value).buildPartial();
        } else {
          serviceAccessPoint_ = value;
        }
        onChanged();
      } else {
        serviceAccessPointBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     */
    public Builder clearServiceAccessPoint() {
      if (serviceAccessPointBuilder_ == null) {
        serviceAccessPoint_ = null;
        onChanged();
      } else {
        serviceAccessPoint_ = null;
        serviceAccessPointBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     */
    public apache.rocketmq.v2.Endpoints.Builder getServiceAccessPointBuilder() {
      
      onChanged();
      return getServiceAccessPointFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     */
    public apache.rocketmq.v2.EndpointsOrBuilder getServiceAccessPointOrBuilder() {
      if (serviceAccessPointBuilder_ != null) {
        return serviceAccessPointBuilder_.getMessageOrBuilder();
      } else {
        return serviceAccessPoint_ == null ?
            apache.rocketmq.v2.Endpoints.getDefaultInstance() : serviceAccessPoint_;
      }
    }
    /**
     * <code>.apache.rocketmq.v2.Endpoints service_access_point = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v2.Endpoints, apache.rocketmq.v2.Endpoints.Builder, apache.rocketmq.v2.EndpointsOrBuilder> 
        getServiceAccessPointFieldBuilder() {
      if (serviceAccessPointBuilder_ == null) {
        serviceAccessPointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v2.Endpoints, apache.rocketmq.v2.Endpoints.Builder, apache.rocketmq.v2.EndpointsOrBuilder>(
                getServiceAccessPoint(),
                getParentForChildren(),
                isClean());
        serviceAccessPoint_ = null;
      }
      return serviceAccessPointBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v2.Trace)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v2.Trace)
  private static final apache.rocketmq.v2.Trace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v2.Trace();
  }

  public static apache.rocketmq.v2.Trace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Trace>
      PARSER = new com.google.protobuf.AbstractParser<Trace>() {
    @java.lang.Override
    public Trace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Trace(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Trace> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Trace> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v2.Trace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

