// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v2/service.proto

package apache.rocketmq.v2;

public interface VerifyMessageResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v2.VerifyMessageResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 command_id = 1;</code>
   * @return The commandId.
   */
  long getCommandId();

  /**
   * <code>.apache.rocketmq.v2.ResponseCommon common = 2;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.apache.rocketmq.v2.ResponseCommon common = 2;</code>
   * @return The common.
   */
  apache.rocketmq.v2.ResponseCommon getCommon();
  /**
   * <code>.apache.rocketmq.v2.ResponseCommon common = 2;</code>
   */
  apache.rocketmq.v2.ResponseCommonOrBuilder getCommonOrBuilder();
}
